import { useState, useEffect, useMemo, useCallback, useRef } from "react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import { Badge } from "@/components/ui/badge"
import { HugeiconsIcon } from "@hugeicons/react"
import {
  CheckmarkCircle01Icon,
  Loading02Icon,
  CancelCircleIcon,
  ComputerIcon,
  HierarchyIcon,
  Link01Icon,
  Copy01Icon,
  Tick02Icon,
} from "@hugeicons/core-free-icons"

import type { ModelInfo } from "@/lib/chat-types"

interface SetupProps {
  onComplete: () => void
}

type DeployMode = "standalone" | "leader" | "worker"
type Step =
  | "mode"
  | "password"
  | "leader-config"
  | "worker-config"
  | "provider"
  | "git-setup"
  | "done"
  | "restarting"

interface ProviderTypeInfo {
  id: string
  name: string
}

export default function Setup({ onComplete }: SetupProps) {
  const [step, setStep] = useState<Step>("mode")
  const [mode, setMode] = useState<DeployMode>("standalone")

  // Password
  const [password, setPassword] = useState("")
  const [confirmPassword, setConfirmPassword] = useState("")

  // Leader config (generated by server)
  const [generatedSwarmCode, setGeneratedSwarmCode] = useState("")

  // Node name (leader + worker)
  const [nodeName, setNodeName] = useState("")

  // Worker config
  const [workerConnectionMethod, setWorkerConnectionMethod] = useState<
    "swarm" | "direct"
  >("swarm")
  const [workerSwarmCode, setWorkerSwarmCode] = useState("")
  const [workerLeaderAddr, setWorkerLeaderAddr] = useState("")
  const [swarmValidation, setSwarmValidation] = useState<
    "idle" | "checking" | "found" | "not_found" | "error"
  >("idle")

  // Provider
  const [providerTypes, setProviderTypes] = useState<ProviderTypeInfo[]>([])
  const [providerType, setProviderType] = useState("")
  const [providerModels, setProviderModels] = useState<ModelInfo[]>([])
  const [apiKey, setApiKey] = useState("")
  const [model, setModel] = useState("")
  const [testStatus, setTestStatus] = useState<
    "idle" | "testing" | "success" | "error"
  >("idle")
  const [testError, setTestError] = useState("")

  // Git & SSH (optional)
  const [gitName, setGitName] = useState("")
  const [gitEmail, setGitEmail] = useState("")
  const [gitHostname, setGitHostname] = useState("")
  const [gitPubkey, setGitPubkey] = useState("")
  const [gitSubmitting, setGitSubmitting] = useState(false)
  const [gitError, setGitError] = useState("")
  const [gitKeyCopied, setGitKeyCopied] = useState(false)

  // General
  const [error, setError] = useState("")
  const [submitting, setSubmitting] = useState(false)
  const [copied, setCopied] = useState(false)

  useEffect(() => {
    fetch("/api/setup/provider-types")
      .then((res) => (res.ok ? res.json() : []))
      .then((types: ProviderTypeInfo[]) => {
        setProviderTypes(types)
        if (types.length > 0) {
          setProviderType((prev) => {
            if (prev) return prev
            const preferred = types.find((t) => t.id === "openrouter")
            return preferred ? preferred.id : types[0].id
          })
        }
      })
      .catch(() => {})
  }, [])

  useEffect(() => {
    if (!providerType) {
      setProviderModels([])
      return
    }
    fetch(`/api/setup/models?provider=${encodeURIComponent(providerType)}`)
      .then((res) => (res.ok ? res.json() : []))
      .then((data: ModelInfo[]) => setProviderModels(data ?? []))
      .catch(() => setProviderModels([]))
  }, [providerType])

  const providerItems = useMemo(
    () => Object.fromEntries(providerTypes.map((p) => [p.id, p.name])),
    [providerTypes]
  )

  const passwordValid = password.length >= 8 && password === confirmPassword

  // Navigation helpers
  const nextAfterPassword = () => {
    switch (mode) {
      case "worker":
        return "worker-config" as Step
      default:
        // Both standalone and leader go to provider config next.
        // Leader's swarm code step comes AFTER setup completes.
        return "provider" as Step
    }
  }

  const handleTestProvider = async () => {
    setTestStatus("testing")
    setTestError("")
    try {
      const res = await fetch("/api/setup/test-provider", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          type: providerType,
          api_key: apiKey,
          model: model || undefined,
        }),
      })
      const data = await res.json()
      if (data.valid) {
        setTestStatus("success")
      } else {
        setTestStatus("error")
        setTestError(data.error || "Connection failed")
      }
    } catch {
      setTestStatus("error")
      setTestError("Network error")
    }
  }

  const handleValidateSwarm = async () => {
    setSwarmValidation("checking")
    try {
      const res = await fetch("/api/setup/validate-swarm", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ swarm_code: workerSwarmCode }),
      })
      const data = await res.json()
      setSwarmValidation(data.leader_found ? "found" : "not_found")
    } catch {
      setSwarmValidation("error")
    }
  }

  const handleCopySwarmCode = useCallback(() => {
    navigator.clipboard.writeText(generatedSwarmCode)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }, [generatedSwarmCode])

  const pollIntervalRef = useRef<ReturnType<typeof setInterval> | null>(null)
  useEffect(() => {
    return () => {
      if (pollIntervalRef.current) clearInterval(pollIntervalRef.current)
    }
  }, [])
  const pollUntilReady = useCallback(() => {
    pollIntervalRef.current = setInterval(async () => {
      try {
        const res = await fetch("/api/health")
        if (res.ok) {
          clearInterval(pollIntervalRef.current!)
          pollIntervalRef.current = null
          onComplete()
        }
      } catch {
        // still restarting
      }
    }, 2000)
  }, [onComplete])

  // handleGitSetup saves name/email and generates an SSH key. Both calls are
  // best-effort — the user can always retry from Settings.
  const handleGitSetup = async () => {
    setGitError("")
    setGitSubmitting(true)
    try {
      const saveRes = await fetch("/api/git-identity", {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          name: gitName.trim(),
          email: gitEmail.trim(),
        }),
      })
      if (!saveRes.ok) {
        const msg = await saveRes.text()
        setGitError(msg || "Failed to save git identity")
        setGitSubmitting(false)
        return
      }
      const keyRes = await fetch("/api/git-identity/ssh-key", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({}),
      })
      if (!keyRes.ok) {
        setGitError("Failed to generate SSH key")
        setGitSubmitting(false)
        return
      }
      const data = await keyRes.json()
      setGitPubkey(data.pubkey || "")
      // refresh hostname from server for the GitHub link title
      try {
        const info = await fetch("/api/git-identity")
        if (info.ok) {
          const d = await info.json()
          if (d.hostname) setGitHostname(d.hostname)
        }
      } catch {
        /* ignore */
      }
    } catch {
      setGitError("Unable to connect to the server")
    } finally {
      setGitSubmitting(false)
    }
  }

  const handleCopyPubkey = useCallback(() => {
    if (!gitPubkey) return
    navigator.clipboard.writeText(gitPubkey)
    setGitKeyCopied(true)
    setTimeout(() => setGitKeyCopied(false), 2000)
  }, [gitPubkey])

  // handleFinish submits the setup request. The server response determines the
  // next step: leader gets a swarm code to display, worker triggers a restart,
  // standalone goes straight to done.
  const handleFinish = async () => {
    setError("")
    setSubmitting(true)

    try {
      const body: Record<string, string> = { password, mode, node_name: nodeName.trim() }

      if (mode !== "worker") {
        body.provider_type = providerType
        body.api_key = apiKey
        if (model) body.default_model = model
      }

      if (mode === "worker") {
        if (workerConnectionMethod === "swarm") {
          body.worker_swarm_code = workerSwarmCode
        } else {
          body.worker_leader_addr = workerLeaderAddr
        }
      }

      const res = await fetch("/api/setup", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      })

      if (res.ok) {
        const data = await res.json()

        if (data.swarm_code) {
          // Leader mode: server generated a swarm code — show it.
          setGeneratedSwarmCode(data.swarm_code)
          setStep("leader-config")
        } else if (data.restart_required) {
          // Worker mode: server is restarting — poll until ready.
          setStep("restarting")
          setTimeout(pollUntilReady, 2000)
        } else {
          // Standalone: offer optional Git & SSH setup before the dashboard.
          setStep("git-setup")
        }
      } else {
        const text = await res.text()
        setError(text || "Setup failed")
      }
    } catch {
      setError("Connection failed")
    } finally {
      setSubmitting(false)
    }
  }

  return (
    <div className="flex min-h-screen items-center justify-center bg-background p-4">
      <Card className="w-full max-w-md">
        {/* Step: Mode Selection */}
        {step === "mode" && (
          <>
            <CardHeader>
              <CardTitle className="text-2xl font-bold">
                Welcome to Hiro
              </CardTitle>
              <CardDescription>
                Choose how you want to run this instance.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="flex flex-col gap-3">
                {(
                  [
                    {
                      id: "standalone" as DeployMode,
                      icon: ComputerIcon,
                      title: "Standalone",
                      desc: "Single node, no remote connections.",
                    },
                    {
                      id: "leader" as DeployMode,
                      icon: HierarchyIcon,
                      title: "Leader",
                      desc: "Run agents and accept worker connections for distributed execution.",
                    },
                    {
                      id: "worker" as DeployMode,
                      icon: Link01Icon,
                      title: "Worker",
                      desc: "Connect to a leader and execute tasks on its behalf.",
                    },
                  ] as const
                ).map((opt) => (
                  <button
                    key={opt.id}
                    onClick={() => {
                      setMode(opt.id)
                      setStep("password")
                    }}
                    className="flex items-start gap-3 rounded-lg border p-4 text-left transition-colors hover:bg-accent"
                  >
                    <HugeiconsIcon
                      icon={opt.icon}
                      className="mt-0.5 h-5 w-5 shrink-0 text-muted-foreground"
                    />
                    <div>
                      <div className="font-medium">{opt.title}</div>
                      <div className="text-sm text-muted-foreground">
                        {opt.desc}
                      </div>
                    </div>
                  </button>
                ))}
              </div>
            </CardContent>
          </>
        )}

        {/* Step: Password */}
        {step === "password" && (
          <>
            <CardHeader>
              <CardTitle>Set Up This Machine</CardTitle>
              <CardDescription>
                Name this machine and secure it with a password.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <form
                onSubmit={(e) => {
                  e.preventDefault()
                  if (passwordValid && nodeName.trim())
                    setStep(nextAfterPassword())
                }}
                className="flex flex-col gap-4"
              >
                <div className="flex flex-col gap-2">
                  <Label htmlFor="setup-nodename">Machine Name</Label>
                  <Input
                    id="setup-nodename"
                    value={nodeName}
                    onChange={(e) => setNodeName(e.target.value)}
                    placeholder="e.g. office-server, gpu-worker-1"
                    autoFocus
                  />
                </div>
                <div className="flex flex-col gap-2">
                  <Label htmlFor="setup-password">Password</Label>
                  <Input
                    id="setup-password"
                    type="password"
                    value={password}
                    onChange={(e) => setPassword(e.target.value)}
                    placeholder="At least 8 characters"
                  />
                </div>
                <div className="flex flex-col gap-2">
                  <Label htmlFor="setup-confirm">Confirm password</Label>
                  <Input
                    id="setup-confirm"
                    type="password"
                    value={confirmPassword}
                    onChange={(e) => setConfirmPassword(e.target.value)}
                    placeholder="Confirm password"
                  />
                  {confirmPassword && password !== confirmPassword && (
                    <p className="text-sm text-destructive">
                      Passwords don&apos;t match
                    </p>
                  )}
                </div>
                <div className="flex gap-2">
                  <Button
                    type="button"
                    variant="outline"
                    onClick={() => setStep("mode")}
                    className="flex-1"
                  >
                    Back
                  </Button>
                  <Button
                    type="submit"
                    disabled={!passwordValid || !nodeName.trim()}
                    className="flex-1"
                  >
                    Continue
                  </Button>
                </div>
              </form>
            </CardContent>
          </>
        )}

        {/* Step: Leader Config (shown AFTER setup completes, displays generated swarm code) */}
        {step === "leader-config" && (
          <>
            <CardHeader>
              <div className="mx-auto mb-2 flex h-12 w-12 items-center justify-center rounded-full bg-green-500/10">
                <HugeiconsIcon
                  icon={CheckmarkCircle01Icon}
                  className="h-6 w-6 text-green-500"
                />
              </div>
              <CardTitle className="text-center">
                Your Leader is Ready
              </CardTitle>
              <CardDescription className="text-center">
                Share this swarm code with your worker nodes so they can find
                this leader.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="flex flex-col gap-4">
                <div className="relative flex items-center justify-center rounded-lg border bg-muted/50 p-4">
                  <code className="text-center text-2xl font-bold tracking-widest">
                    {generatedSwarmCode.toUpperCase()}
                  </code>
                  <Button
                    variant="ghost"
                    size="sm"
                    className="absolute right-2"
                    onClick={handleCopySwarmCode}
                  >
                    <HugeiconsIcon
                      icon={copied ? Tick02Icon : Copy01Icon}
                      className="h-4 w-4"
                    />
                  </Button>
                </div>
                <p className="text-center text-sm text-muted-foreground">
                  Workers will enter this code during their setup to connect to
                  this leader.
                </p>
                <Button onClick={() => setStep("git-setup")} className="w-full">
                  Continue
                </Button>
              </div>
            </CardContent>
          </>
        )}

        {/* Step: Worker Config */}
        {step === "worker-config" && (
          <>
            <CardHeader>
              <CardTitle>Connect to Leader</CardTitle>
              <CardDescription>
                Enter the swarm code from your leader, or connect directly.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="flex flex-col gap-4">
                <div className="flex gap-2">
                  <Button
                    variant={
                      workerConnectionMethod === "swarm" ? "default" : "outline"
                    }
                    size="sm"
                    onClick={() => setWorkerConnectionMethod("swarm")}
                    className="flex-1"
                  >
                    Swarm Code
                  </Button>
                  <Button
                    variant={
                      workerConnectionMethod === "direct"
                        ? "default"
                        : "outline"
                    }
                    size="sm"
                    onClick={() => setWorkerConnectionMethod("direct")}
                    className="flex-1"
                  >
                    Direct Connection
                  </Button>
                </div>

                {workerConnectionMethod === "swarm" && (
                  <div className="flex flex-col gap-3">
                    <div className="flex flex-col gap-2">
                      <Label htmlFor="worker-swarm">Swarm Code</Label>
                      <Input
                        id="worker-swarm"
                        value={workerSwarmCode}
                        onChange={(e) => {
                          setWorkerSwarmCode(e.target.value)
                          setSwarmValidation("idle")
                        }}
                        placeholder="e.g. hk7m-q3fx"
                        autoFocus
                      />
                    </div>
                    <div className="flex items-center gap-2">
                      <Button
                        variant="outline"
                        onClick={handleValidateSwarm}
                        disabled={
                          !workerSwarmCode ||
                          swarmValidation === "checking"
                        }
                        className="flex-1"
                      >
                        {swarmValidation === "checking" && (
                          <HugeiconsIcon
                            icon={Loading02Icon}
                            className="mr-2 h-4 w-4 animate-spin"
                          />
                        )}
                        Verify
                      </Button>
                      {swarmValidation === "found" && (
                        <Badge
                          variant="outline"
                          className="gap-1 border-green-500 text-green-500"
                        >
                          <HugeiconsIcon
                            icon={CheckmarkCircle01Icon}
                            className="h-3 w-3"
                          />
                          Leader found
                        </Badge>
                      )}
                      {swarmValidation === "not_found" && (
                        <Badge
                          variant="outline"
                          className="gap-1 border-destructive text-destructive"
                        >
                          <HugeiconsIcon
                            icon={CancelCircleIcon}
                            className="h-3 w-3"
                          />
                          No leader found
                        </Badge>
                      )}
                    </div>
                  </div>
                )}

                {workerConnectionMethod === "direct" && (
                  <div className="flex flex-col gap-3">
                    <div className="flex flex-col gap-2">
                      <Label htmlFor="worker-addr">Leader Address</Label>
                      <Input
                        id="worker-addr"
                        value={workerLeaderAddr}
                        onChange={(e) => setWorkerLeaderAddr(e.target.value)}
                        placeholder="e.g. 10.0.0.1:8121"
                        autoFocus
                      />
                    </div>
                    <p className="text-sm text-muted-foreground">
                      The leader will need to approve this machine before it can
                      connect.
                    </p>
                  </div>
                )}

                {error && <p className="text-sm text-destructive">{error}</p>}

                <div className="flex gap-2">
                  <Button
                    variant="outline"
                    onClick={() => setStep("password")}
                    className="flex-1"
                  >
                    Back
                  </Button>
                  <Button
                    onClick={handleFinish}
                    disabled={
                      submitting ||
                      (workerConnectionMethod === "swarm"
                        ? !workerSwarmCode
                        : !workerLeaderAddr)
                    }
                    className="flex-1"
                  >
                    {submitting && (
                      <HugeiconsIcon
                        icon={Loading02Icon}
                        className="mr-2 h-4 w-4 animate-spin"
                      />
                    )}
                    Complete Setup
                  </Button>
                </div>
              </div>
            </CardContent>
          </>
        )}

        {/* Step: Provider Config (standalone + leader) */}
        {step === "provider" && (
          <>
            <CardHeader>
              <CardTitle>Configure LLM Provider</CardTitle>
              <CardDescription>
                Connect your AI provider to power your agents.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <form
                onSubmit={(e) => {
                  e.preventDefault()
                  if (apiKey && !submitting) handleFinish()
                }}
                className="flex flex-col gap-4"
              >
                <div className="flex flex-col gap-2">
                  <Label>Provider</Label>
                  <Select
                    value={providerType}
                    onValueChange={(v) => {
                      if (v) {
                        setProviderType(v)
                        setModel("")
                      }
                      setTestStatus("idle")
                    }}
                    items={providerItems}
                  >
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      {providerTypes.map((p) => (
                        <SelectItem key={p.id} value={p.id}>
                          {p.name}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
                <div className="flex flex-col gap-2">
                  <Label htmlFor="setup-apikey">API Key</Label>
                  <Input
                    id="setup-apikey"
                    type="password"
                    value={apiKey}
                    onChange={(e) => {
                      setApiKey(e.target.value)
                      setTestStatus("idle")
                    }}
                    placeholder="Enter your API key"
                  />
                </div>
                {providerModels.length > 0 && (
                  <div className="flex flex-col gap-2">
                    <Label>
                      Default Model{" "}
                      <span className="text-muted-foreground">(optional)</span>
                    </Label>
                    <Select
                      value={model}
                      onValueChange={(v) => setModel(v ?? "")}
                      items={Object.fromEntries(
                        providerModels.map((m) => [m.id, m.name || m.id])
                      )}
                    >
                      <SelectTrigger className="w-full">
                        <SelectValue placeholder="Provider default" />
                      </SelectTrigger>
                      <SelectContent>
                        {providerModels.map((m) => (
                          <SelectItem key={m.id} value={m.id}>
                            {m.name || m.id}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>
                )}

                <div className="flex items-center gap-2">
                  <Button
                    variant="outline"
                    onClick={handleTestProvider}
                    disabled={!apiKey || testStatus === "testing"}
                    className="flex-1"
                    type="button"
                  >
                    {testStatus === "testing" && (
                      <HugeiconsIcon
                        icon={Loading02Icon}
                        className="mr-2 h-4 w-4 animate-spin"
                      />
                    )}
                    Test Connection
                  </Button>
                  {testStatus === "success" && (
                    <Badge
                      variant="outline"
                      className="gap-1 border-green-500 text-green-500"
                    >
                      <HugeiconsIcon
                        icon={CheckmarkCircle01Icon}
                        className="h-3 w-3"
                      />
                      Connected
                    </Badge>
                  )}
                  {testStatus === "error" && (
                    <Badge
                      variant="outline"
                      className="gap-1 border-destructive text-destructive"
                    >
                      <HugeiconsIcon
                        icon={CancelCircleIcon}
                        className="h-3 w-3"
                      />
                      Failed
                    </Badge>
                  )}
                </div>
                {testError && (
                  <p className="text-sm text-destructive">{testError}</p>
                )}

                {error && <p className="text-sm text-destructive">{error}</p>}

                <div className="flex gap-2">
                  <Button
                    type="button"
                    variant="outline"
                    onClick={() => setStep("password")}
                    className="flex-1"
                  >
                    Back
                  </Button>
                  <Button
                    type="submit"
                    disabled={!apiKey || submitting}
                    className="flex-1"
                  >
                    {submitting ? (
                      <HugeiconsIcon
                        icon={Loading02Icon}
                        className="mr-2 h-4 w-4 animate-spin"
                      />
                    ) : null}
                    Complete Setup
                  </Button>
                </div>
              </form>
            </CardContent>
          </>
        )}

        {/* Step: Git & SSH (optional, shown after setup) */}
        {step === "git-setup" && (
          <>
            <CardHeader>
              <CardTitle>Git &amp; SSH</CardTitle>
              <CardDescription>
                Optional. Set this up so your agents can clone, commit, and
                push without extra configuration. You can always change this
                later in Settings.
              </CardDescription>
            </CardHeader>
            <CardContent>
              {!gitPubkey ? (
                <form
                  className="flex flex-col gap-4"
                  onSubmit={(e) => {
                    e.preventDefault()
                    handleGitSetup()
                  }}
                >
                  <div className="flex flex-col gap-2">
                    <Label htmlFor="git-name">Your name</Label>
                    <Input
                      id="git-name"
                      value={gitName}
                      onChange={(e) => setGitName(e.target.value)}
                      placeholder="Ada Lovelace"
                      disabled={gitSubmitting}
                    />
                  </div>
                  <div className="flex flex-col gap-2">
                    <Label htmlFor="git-email">Email</Label>
                    <Input
                      id="git-email"
                      type="email"
                      value={gitEmail}
                      onChange={(e) => setGitEmail(e.target.value)}
                      placeholder="ada@example.com"
                      disabled={gitSubmitting}
                    />
                  </div>
                  {gitError && (
                    <p className="text-sm text-destructive">{gitError}</p>
                  )}
                  <div className="flex flex-col gap-2">
                    <Button
                      type="submit"
                      disabled={
                        gitSubmitting || !gitName.trim() || !gitEmail.trim()
                      }
                      className="w-full"
                    >
                      {gitSubmitting ? (
                        <HugeiconsIcon
                          icon={Loading02Icon}
                          className="mr-2 h-4 w-4 animate-spin"
                        />
                      ) : null}
                      Generate SSH key &amp; continue
                    </Button>
                    <Button
                      type="button"
                      variant="ghost"
                      onClick={onComplete}
                      disabled={gitSubmitting}
                      className="w-full"
                    >
                      Skip for now
                    </Button>
                  </div>
                </form>
              ) : (
                <div className="flex flex-col gap-4">
                  <div>
                    <Label>Your SSH public key</Label>
                    <div className="relative mt-2">
                      <pre className="rounded-md border bg-muted p-3 pr-12 text-xs break-all whitespace-pre-wrap">
                        {gitPubkey}
                      </pre>
                      <Button
                        variant="ghost"
                        size="icon"
                        className="absolute top-1 right-1"
                        onClick={handleCopyPubkey}
                        aria-label="Copy public key"
                      >
                        <HugeiconsIcon
                          icon={gitKeyCopied ? Tick02Icon : Copy01Icon}
                        />
                      </Button>
                    </div>
                  </div>
                  <p className="text-sm text-muted-foreground">
                    Paste this into GitHub to let your agents push to your
                    repos.
                  </p>
                  <Button
                    variant="outline"
                    className="w-full"
                    onClick={() =>
                      window.open(
                        `https://github.com/settings/ssh/new?title=${encodeURIComponent("hiro@" + (gitHostname || "hiro"))}`,
                        "_blank",
                        "noreferrer"
                      )
                    }
                  >
                    Add to GitHub
                  </Button>
                  <p className="text-xs text-muted-foreground">
                    For GitHub CLI, run <code>gh auth login</code> in a
                    terminal — <code>gh</code> is already installed.
                  </p>
                  <Button onClick={onComplete} className="w-full">
                    Go to Dashboard
                  </Button>
                </div>
              )}
            </CardContent>
          </>
        )}

        {/* Step: Done (standalone) */}
        {step === "done" && (
          <>
            <CardHeader className="text-center">
              <div className="mx-auto mb-2 flex h-12 w-12 items-center justify-center rounded-full bg-green-500/10">
                <HugeiconsIcon
                  icon={CheckmarkCircle01Icon}
                  className="h-6 w-6 text-green-500"
                />
              </div>
              <CardTitle>You&apos;re all set!</CardTitle>
              <CardDescription>
                Hiro is configured and ready to use.
              </CardDescription>
            </CardHeader>
          </>
        )}

        {/* Step: Restarting (worker mode) */}
        {step === "restarting" && (
          <>
            <CardHeader className="text-center">
              <div className="mx-auto mb-2 flex h-12 w-12 items-center justify-center">
                <HugeiconsIcon
                  icon={Loading02Icon}
                  className="h-6 w-6 animate-spin text-muted-foreground"
                />
              </div>
              <CardTitle>Connecting to Leader...</CardTitle>
              <CardDescription>
                Hiro is restarting in worker mode. This page will refresh
                automatically.
              </CardDescription>
            </CardHeader>
          </>
        )}
      </Card>
    </div>
  )
}
