// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: internal/ipc/proto/hiro.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentWorker_ExecuteTool_FullMethodName = "/hiro.AgentWorker/ExecuteTool"
	AgentWorker_Shutdown_FullMethodName    = "/hiro.AgentWorker/Shutdown"
	AgentWorker_WatchJobs_FullMethodName   = "/hiro.AgentWorker/WatchJobs"
)

// AgentWorkerClient is the client API for AgentWorker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentWorker is served by each agent worker process. The control plane
// calls these RPCs to execute tools and manage the worker's lifecycle.
type AgentWorkerClient interface {
	// ExecuteTool runs a single tool in the worker's sandbox and returns the result.
	ExecuteTool(ctx context.Context, in *ExecuteToolRequest, opts ...grpc.CallOption) (*ExecuteToolResponse, error)
	// Shutdown gracefully stops the agent worker process.
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error)
	// WatchJobs streams background job completion events from the worker.
	// The control plane uses this to push notifications into the inference loop.
	WatchJobs(ctx context.Context, in *WatchJobsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JobCompletion], error)
}

type agentWorkerClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentWorkerClient(cc grpc.ClientConnInterface) AgentWorkerClient {
	return &agentWorkerClient{cc}
}

func (c *agentWorkerClient) ExecuteTool(ctx context.Context, in *ExecuteToolRequest, opts ...grpc.CallOption) (*ExecuteToolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteToolResponse)
	err := c.cc.Invoke(ctx, AgentWorker_ExecuteTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentWorkerClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShutdownResponse)
	err := c.cc.Invoke(ctx, AgentWorker_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentWorkerClient) WatchJobs(ctx context.Context, in *WatchJobsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JobCompletion], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentWorker_ServiceDesc.Streams[0], AgentWorker_WatchJobs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchJobsRequest, JobCompletion]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentWorker_WatchJobsClient = grpc.ServerStreamingClient[JobCompletion]

// AgentWorkerServer is the server API for AgentWorker service.
// All implementations must embed UnimplementedAgentWorkerServer
// for forward compatibility.
//
// AgentWorker is served by each agent worker process. The control plane
// calls these RPCs to execute tools and manage the worker's lifecycle.
type AgentWorkerServer interface {
	// ExecuteTool runs a single tool in the worker's sandbox and returns the result.
	ExecuteTool(context.Context, *ExecuteToolRequest) (*ExecuteToolResponse, error)
	// Shutdown gracefully stops the agent worker process.
	Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error)
	// WatchJobs streams background job completion events from the worker.
	// The control plane uses this to push notifications into the inference loop.
	WatchJobs(*WatchJobsRequest, grpc.ServerStreamingServer[JobCompletion]) error
	mustEmbedUnimplementedAgentWorkerServer()
}

// UnimplementedAgentWorkerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentWorkerServer struct{}

func (UnimplementedAgentWorkerServer) ExecuteTool(context.Context, *ExecuteToolRequest) (*ExecuteToolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteTool not implemented")
}
func (UnimplementedAgentWorkerServer) Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedAgentWorkerServer) WatchJobs(*WatchJobsRequest, grpc.ServerStreamingServer[JobCompletion]) error {
	return status.Error(codes.Unimplemented, "method WatchJobs not implemented")
}
func (UnimplementedAgentWorkerServer) mustEmbedUnimplementedAgentWorkerServer() {}
func (UnimplementedAgentWorkerServer) testEmbeddedByValue()                     {}

// UnsafeAgentWorkerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentWorkerServer will
// result in compilation errors.
type UnsafeAgentWorkerServer interface {
	mustEmbedUnimplementedAgentWorkerServer()
}

func RegisterAgentWorkerServer(s grpc.ServiceRegistrar, srv AgentWorkerServer) {
	// If the following call panics, it indicates UnimplementedAgentWorkerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentWorker_ServiceDesc, srv)
}

func _AgentWorker_ExecuteTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentWorkerServer).ExecuteTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentWorker_ExecuteTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentWorkerServer).ExecuteTool(ctx, req.(*ExecuteToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentWorker_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentWorkerServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentWorker_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentWorkerServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentWorker_WatchJobs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchJobsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentWorkerServer).WatchJobs(m, &grpc.GenericServerStream[WatchJobsRequest, JobCompletion]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentWorker_WatchJobsServer = grpc.ServerStreamingServer[JobCompletion]

// AgentWorker_ServiceDesc is the grpc.ServiceDesc for AgentWorker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentWorker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hiro.AgentWorker",
	HandlerType: (*AgentWorkerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteTool",
			Handler:    _AgentWorker_ExecuteTool_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _AgentWorker_Shutdown_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchJobs",
			Handler:       _AgentWorker_WatchJobs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/ipc/proto/hiro.proto",
}

const (
	Cluster_NodeStream_FullMethodName = "/hiro.Cluster/NodeStream"
)

// ClusterClient is the client API for Cluster service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Cluster is served by the leader. Worker nodes dial the leader and open
// a long-lived bidirectional stream for spawning workers, executing tools,
// and receiving file sync updates.
type ClusterClient interface {
	// NodeStream is a bidirectional stream between a worker node and the
	// leader. The node sends registration, tool results, and heartbeats.
	// The leader sends spawn commands, tool execution requests, and file sync.
	NodeStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[NodeMessage, LeaderMessage], error)
}

type clusterClient struct {
	cc grpc.ClientConnInterface
}

func NewClusterClient(cc grpc.ClientConnInterface) ClusterClient {
	return &clusterClient{cc}
}

func (c *clusterClient) NodeStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[NodeMessage, LeaderMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Cluster_ServiceDesc.Streams[0], Cluster_NodeStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[NodeMessage, LeaderMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Cluster_NodeStreamClient = grpc.BidiStreamingClient[NodeMessage, LeaderMessage]

// ClusterServer is the server API for Cluster service.
// All implementations must embed UnimplementedClusterServer
// for forward compatibility.
//
// Cluster is served by the leader. Worker nodes dial the leader and open
// a long-lived bidirectional stream for spawning workers, executing tools,
// and receiving file sync updates.
type ClusterServer interface {
	// NodeStream is a bidirectional stream between a worker node and the
	// leader. The node sends registration, tool results, and heartbeats.
	// The leader sends spawn commands, tool execution requests, and file sync.
	NodeStream(grpc.BidiStreamingServer[NodeMessage, LeaderMessage]) error
	mustEmbedUnimplementedClusterServer()
}

// UnimplementedClusterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClusterServer struct{}

func (UnimplementedClusterServer) NodeStream(grpc.BidiStreamingServer[NodeMessage, LeaderMessage]) error {
	return status.Error(codes.Unimplemented, "method NodeStream not implemented")
}
func (UnimplementedClusterServer) mustEmbedUnimplementedClusterServer() {}
func (UnimplementedClusterServer) testEmbeddedByValue()                 {}

// UnsafeClusterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClusterServer will
// result in compilation errors.
type UnsafeClusterServer interface {
	mustEmbedUnimplementedClusterServer()
}

func RegisterClusterServer(s grpc.ServiceRegistrar, srv ClusterServer) {
	// If the following call panics, it indicates UnimplementedClusterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Cluster_ServiceDesc, srv)
}

func _Cluster_NodeStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ClusterServer).NodeStream(&grpc.GenericServerStream[NodeMessage, LeaderMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Cluster_NodeStreamServer = grpc.BidiStreamingServer[NodeMessage, LeaderMessage]

// Cluster_ServiceDesc is the grpc.ServiceDesc for Cluster service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Cluster_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hiro.Cluster",
	HandlerType: (*ClusterServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "NodeStream",
			Handler:       _Cluster_NodeStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "internal/ipc/proto/hiro.proto",
}
