// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: internal/ipc/proto/hiro.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WatchJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchJobsRequest) Reset() {
	*x = WatchJobsRequest{}
	mi := &file_internal_ipc_proto_hiro_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchJobsRequest) ProtoMessage() {}

func (x *WatchJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_proto_hiro_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchJobsRequest.ProtoReflect.Descriptor instead.
func (*WatchJobsRequest) Descriptor() ([]byte, []int) {
	return file_internal_ipc_proto_hiro_proto_rawDescGZIP(), []int{0}
}

type JobCompletion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ExitCode      int32                  `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Failed        bool                   `protobuf:"varint,5,opt,name=failed,proto3" json:"failed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobCompletion) Reset() {
	*x = JobCompletion{}
	mi := &file_internal_ipc_proto_hiro_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobCompletion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobCompletion) ProtoMessage() {}

func (x *JobCompletion) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_proto_hiro_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobCompletion.ProtoReflect.Descriptor instead.
func (*JobCompletion) Descriptor() ([]byte, []int) {
	return file_internal_ipc_proto_hiro_proto_rawDescGZIP(), []int{1}
}

func (x *JobCompletion) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *JobCompletion) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *JobCompletion) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *JobCompletion) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *JobCompletion) GetFailed() bool {
	if x != nil {
		return x.Failed
	}
	return false
}

type ExecuteToolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                            // tool name (Bash, Read, etc.)
	Input         string                 `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`                          // JSON-encoded tool arguments
	CallId        string                 `protobuf:"bytes,3,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`          // tool call ID from the LLM
	SecretEnv     []string               `protobuf:"bytes,4,rep,name=secret_env,json=secretEnv,proto3" json:"secret_env,omitempty"` // secret env vars for Bash (KEY=VALUE pairs)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteToolRequest) Reset() {
	*x = ExecuteToolRequest{}
	mi := &file_internal_ipc_proto_hiro_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteToolRequest) ProtoMessage() {}

func (x *ExecuteToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_proto_hiro_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteToolRequest.ProtoReflect.Descriptor instead.
func (*ExecuteToolRequest) Descriptor() ([]byte, []int) {
	return file_internal_ipc_proto_hiro_proto_rawDescGZIP(), []int{2}
}

func (x *ExecuteToolRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExecuteToolRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *ExecuteToolRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *ExecuteToolRequest) GetSecretEnv() []string {
	if x != nil {
		return x.SecretEnv
	}
	return nil
}

type ExecuteToolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	IsError       bool                   `protobuf:"varint,2,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteToolResponse) Reset() {
	*x = ExecuteToolResponse{}
	mi := &file_internal_ipc_proto_hiro_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteToolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteToolResponse) ProtoMessage() {}

func (x *ExecuteToolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_proto_hiro_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteToolResponse.ProtoReflect.Descriptor instead.
func (*ExecuteToolResponse) Descriptor() ([]byte, []int) {
	return file_internal_ipc_proto_hiro_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteToolResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ExecuteToolResponse) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_internal_ipc_proto_hiro_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_proto_hiro_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_internal_ipc_proto_hiro_proto_rawDescGZIP(), []int{4}
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_internal_ipc_proto_hiro_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_proto_hiro_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_internal_ipc_proto_hiro_proto_rawDescGZIP(), []int{5}
}

// NodeMessage is sent from a worker node to the leader.
type NodeMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*NodeMessage_Register
	//	*NodeMessage_SpawnResult
	//	*NodeMessage_ToolResult
	//	*NodeMessage_Heartbeat
	//	*NodeMessage_WorkerExited
	//	*NodeMessage_FileUpdate
	//	*NodeMessage_FileSyncAck
	//	*NodeMessage_JobCompletion
	//	*NodeMessage_TerminalCreated
	//	*NodeMessage_TerminalOutput
	//	*NodeMessage_TerminalExited
	Msg           isNodeMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeMessage) Reset() {
	*x = NodeMessage{}
	mi := &file_internal_ipc_proto_hiro_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeMessage) ProtoMessage() {}

func (x *NodeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_proto_hiro_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeMessage.ProtoReflect.Descriptor instead.
func (*NodeMessage) Descriptor() ([]byte, []int) {
	return file_internal_ipc_proto_hiro_proto_rawDescGZIP(), []int{6}
}

func (x *NodeMessage) GetMsg() isNodeMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *NodeMessage) GetRegister() *NodeRegister {
	if x != nil {
		if x, ok := x.Msg.(*NodeMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *NodeMessage) GetSpawnResult() *SpawnResult {
	if x != nil {
		if x, ok := x.Msg.(*NodeMessage_SpawnResult); ok {
			return x.SpawnResult
		}
	}
	return nil
}

func (x *NodeMessage) GetToolResult() *NodeToolResult {
	if x != nil {
		if x, ok := x.Msg.(*NodeMessage_ToolResult); ok {
			return x.ToolResult
		}
	}
	return nil
}

func (x *NodeMessage) GetHeartbeat() *NodeHeartbeat {
	if x != nil {
		if x, ok := x.Msg.(*NodeMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *NodeMessage) GetWorkerExited() *WorkerExited {
	if x != nil {
		if x, ok := x.Msg.(*NodeMessage_WorkerExited); ok {
			return x.WorkerExited
		}
	}
	return nil
}

func (x *NodeMessage) GetFileUpdate() *FileUpdate {
	if x != nil {
		if x, ok := x.Msg.(*NodeMessage_FileUpdate); ok {
			return x.FileUpdate
		}
	}
	return nil
}

func (x *NodeMessage) GetFileSyncAck() *FileSyncAck {
	if x != nil {
		if x, ok := x.Msg.(*NodeMessage_FileSyncAck); ok {
			return x.FileSyncAck
		}
	}
	return nil
}

func (x *NodeMessage) GetJobCompletion() *JobCompletionNotify {
	if x != nil {
		if x, ok := x.Msg.(*NodeMessage_JobCompletion); ok {
			return x.JobCompletion
		}
	}
	return nil
}

func (x *NodeMessage) GetTerminalCreated() *TerminalCreated {
	if x != nil {
		if x, ok := x.Msg.(*NodeMessage_TerminalCreated); ok {
			return x.TerminalCreated
		}
	}
	return nil
}

func (x *NodeMessage) GetTerminalOutput() *TerminalOutput {
	if x != nil {
		if x, ok := x.Msg.(*NodeMessage_TerminalOutput); ok {
			return x.TerminalOutput
		}
	}
	return nil
}

func (x *NodeMessage) GetTerminalExited() *TerminalExited {
	if x != nil {
		if x, ok := x.Msg.(*NodeMessage_TerminalExited); ok {
			return x.TerminalExited
		}
	}
	return nil
}

type isNodeMessage_Msg interface {
	isNodeMessage_Msg()
}

type NodeMessage_Register struct {
	Register *NodeRegister `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type NodeMessage_SpawnResult struct {
	SpawnResult *SpawnResult `protobuf:"bytes,2,opt,name=spawn_result,json=spawnResult,proto3,oneof"`
}

type NodeMessage_ToolResult struct {
	ToolResult *NodeToolResult `protobuf:"bytes,3,opt,name=tool_result,json=toolResult,proto3,oneof"`
}

type NodeMessage_Heartbeat struct {
	Heartbeat *NodeHeartbeat `protobuf:"bytes,4,opt,name=heartbeat,proto3,oneof"`
}

type NodeMessage_WorkerExited struct {
	WorkerExited *WorkerExited `protobuf:"bytes,5,opt,name=worker_exited,json=workerExited,proto3,oneof"`
}

type NodeMessage_FileUpdate struct {
	FileUpdate *FileUpdate `protobuf:"bytes,6,opt,name=file_update,json=fileUpdate,proto3,oneof"` // worker → leader: file changed on this node
}

type NodeMessage_FileSyncAck struct {
	FileSyncAck *FileSyncAck `protobuf:"bytes,7,opt,name=file_sync_ack,json=fileSyncAck,proto3,oneof"` // worker → leader: initial sync received
}

type NodeMessage_JobCompletion struct {
	JobCompletion *JobCompletionNotify `protobuf:"bytes,8,opt,name=job_completion,json=jobCompletion,proto3,oneof"` // worker → leader: background task completed
}

type NodeMessage_TerminalCreated struct {
	TerminalCreated *TerminalCreated `protobuf:"bytes,9,opt,name=terminal_created,json=terminalCreated,proto3,oneof"` // worker → leader: terminal session created
}

type NodeMessage_TerminalOutput struct {
	TerminalOutput *TerminalOutput `protobuf:"bytes,10,opt,name=terminal_output,json=terminalOutput,proto3,oneof"` // worker → leader: PTY output data
}

type NodeMessage_TerminalExited struct {
	TerminalExited *TerminalExited `protobuf:"bytes,11,opt,name=terminal_exited,json=terminalExited,proto3,oneof"` // worker → leader: terminal shell exited
}

func (*NodeMessage_Register) isNodeMessage_Msg() {}

func (*NodeMessage_SpawnResult) isNodeMessage_Msg() {}

func (*NodeMessage_ToolResult) isNodeMessage_Msg() {}

func (*NodeMessage_Heartbeat) isNodeMessage_Msg() {}

func (*NodeMessage_WorkerExited) isNodeMessage_Msg() {}

func (*NodeMessage_FileUpdate) isNodeMessage_Msg() {}

func (*NodeMessage_FileSyncAck) isNodeMessage_Msg() {}

func (*NodeMessage_JobCompletion) isNodeMessage_Msg() {}

func (*NodeMessage_TerminalCreated) isNodeMessage_Msg() {}

func (*NodeMessage_TerminalOutput) isNodeMessage_Msg() {}

func (*NodeMessage_TerminalExited) isNodeMessage_Msg() {}

type JobCompletionNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Command       string                 `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ExitCode      int32                  `protobuf:"varint,5,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Failed        bool                   `protobuf:"varint,6,opt,name=failed,proto3" json:"failed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobCompletionNotify) Reset() {
	*x = JobCompletionNotify{}
	mi := &file_internal_ipc_proto_hiro_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobCompletionNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobCompletionNotify) ProtoMessage() {}

func (x *JobCompletionNotify) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_proto_hiro_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobCompletionNotify.ProtoReflect.Descriptor instead.
func (*JobCompletionNotify) Descriptor() ([]byte, []int) {
	return file_internal_ipc_proto_hiro_proto_rawDescGZIP(), []int{7}
}

func (x *JobCompletionNotify) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *JobCompletionNotify) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *JobCompletionNotify) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *JobCompletionNotify) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *JobCompletionNotify) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *JobCompletionNotify) GetFailed() bool {
	if x != nil {
		return x.Failed
	}
	return false
}

type FileSyncAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileSyncAck) Reset() {
	*x = FileSyncAck{}
	mi := &file_internal_ipc_proto_hiro_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileSyncAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileSyncAck) ProtoMessage() {}

func (x *FileSyncAck) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_proto_hiro_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileSyncAck.ProtoReflect.Descriptor instead.
func (*FileSyncAck) Descriptor() ([]byte, []int) {
	return file_internal_ipc_proto_hiro_proto_rawDescGZIP(), []int{8}
}

// LeaderMessage is sent from the leader to a worker node.
type LeaderMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*LeaderMessage_Registered
	//	*LeaderMessage_SpawnWorker
	//	*LeaderMessage_ExecuteTool
	//	*LeaderMessage_ShutdownWorker
	//	*LeaderMessage_KillWorker
	//	*LeaderMessage_FileSync
	//	*LeaderMessage_FileUpdate
	//	*LeaderMessage_Pending
	//	*LeaderMessage_Rejected
	//	*LeaderMessage_CreateTerminal
	//	*LeaderMessage_TerminalInput
	//	*LeaderMessage_TerminalResize
	//	*LeaderMessage_CloseTerminal
	Msg           isLeaderMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderMessage) Reset() {
	*x = LeaderMessage{}
	mi := &file_internal_ipc_proto_hiro_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderMessage) ProtoMessage() {}

func (x *LeaderMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_proto_hiro_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderMessage.ProtoReflect.Descriptor instead.
func (*LeaderMessage) Descriptor() ([]byte, []int) {
	return file_internal_ipc_proto_hiro_proto_rawDescGZIP(), []int{9}
}

func (x *LeaderMessage) GetMsg() isLeaderMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *LeaderMessage) GetRegistered() *NodeRegistered {
	if x != nil {
		if x, ok := x.Msg.(*LeaderMessage_Registered); ok {
			return x.Registered
		}
	}
	return nil
}

func (x *LeaderMessage) GetSpawnWorker() *SpawnWorker {
	if x != nil {
		if x, ok := x.Msg.(*LeaderMessage_SpawnWorker); ok {
			return x.SpawnWorker
		}
	}
	return nil
}

func (x *LeaderMessage) GetExecuteTool() *ExecuteToolRemote {
	if x != nil {
		if x, ok := x.Msg.(*LeaderMessage_ExecuteTool); ok {
			return x.ExecuteTool
		}
	}
	return nil
}

func (x *LeaderMessage) GetShutdownWorker() *ShutdownWorker {
	if x != nil {
		if x, ok := x.Msg.(*LeaderMessage_ShutdownWorker); ok {
			return x.ShutdownWorker
		}
	}
	return nil
}

func (x *LeaderMessage) GetKillWorker() *KillWorker {
	if x != nil {
		if x, ok := x.Msg.(*LeaderMessage_KillWorker); ok {
			return x.KillWorker
		}
	}
	return nil
}

func (x *LeaderMessage) GetFileSync() *FileSyncData {
	if x != nil {
		if x, ok := x.Msg.(*LeaderMessage_FileSync); ok {
			return x.FileSync
		}
	}
	return nil
}

func (x *LeaderMessage) GetFileUpdate() *FileUpdate {
	if x != nil {
		if x, ok := x.Msg.(*LeaderMessage_FileUpdate); ok {
			return x.FileUpdate
		}
	}
	return nil
}

func (x *LeaderMessage) GetPending() *NodePending {
	if x != nil {
		if x, ok := x.Msg.(*LeaderMessage_Pending); ok {
			return x.Pending
		}
	}
	return nil
}

func (x *LeaderMessage) GetRejected() *NodeRejected {
	if x != nil {
		if x, ok := x.Msg.(*LeaderMessage_Rejected); ok {
			return x.Rejected
		}
	}
	return nil
}

func (x *LeaderMessage) GetCreateTerminal() *CreateTerminal {
	if x != nil {
		if x, ok := x.Msg.(*LeaderMessage_CreateTerminal); ok {
			return x.CreateTerminal
		}
	}
	return nil
}

func (x *LeaderMessage) GetTerminalInput() *TerminalInput {
	if x != nil {
		if x, ok := x.Msg.(*LeaderMessage_TerminalInput); ok {
			return x.TerminalInput
		}
	}
	return nil
}

func (x *LeaderMessage) GetTerminalResize() *TerminalResize {
	if x != nil {
		if x, ok := x.Msg.(*LeaderMessage_TerminalResize); ok {
			return x.TerminalResize
		}
	}
	return nil
}

func (x *LeaderMessage) GetCloseTerminal() *CloseTerminal {
	if x != nil {
		if x, ok := x.Msg.(*LeaderMessage_CloseTerminal); ok {
			return x.CloseTerminal
		}
	}
	return nil
}

type isLeaderMessage_Msg interface {
	isLeaderMessage_Msg()
}

type LeaderMessage_Registered struct {
	Registered *NodeRegistered `protobuf:"bytes,1,opt,name=registered,proto3,oneof"`
}

type LeaderMessage_SpawnWorker struct {
	SpawnWorker *SpawnWorker `protobuf:"bytes,2,opt,name=spawn_worker,json=spawnWorker,proto3,oneof"`
}

type LeaderMessage_ExecuteTool struct {
	ExecuteTool *ExecuteToolRemote `protobuf:"bytes,3,opt,name=execute_tool,json=executeTool,proto3,oneof"`
}

type LeaderMessage_ShutdownWorker struct {
	ShutdownWorker *ShutdownWorker `protobuf:"bytes,4,opt,name=shutdown_worker,json=shutdownWorker,proto3,oneof"`
}

type LeaderMessage_KillWorker struct {
	KillWorker *KillWorker `protobuf:"bytes,5,opt,name=kill_worker,json=killWorker,proto3,oneof"`
}

type LeaderMessage_FileSync struct {
	FileSync *FileSyncData `protobuf:"bytes,6,opt,name=file_sync,json=fileSync,proto3,oneof"`
}

type LeaderMessage_FileUpdate struct {
	FileUpdate *FileUpdate `protobuf:"bytes,7,opt,name=file_update,json=fileUpdate,proto3,oneof"`
}

type LeaderMessage_Pending struct {
	Pending *NodePending `protobuf:"bytes,8,opt,name=pending,proto3,oneof"`
}

type LeaderMessage_Rejected struct {
	Rejected *NodeRejected `protobuf:"bytes,9,opt,name=rejected,proto3,oneof"`
}

type LeaderMessage_CreateTerminal struct {
	CreateTerminal *CreateTerminal `protobuf:"bytes,10,opt,name=create_terminal,json=createTerminal,proto3,oneof"` // leader → worker: open terminal PTY
}

type LeaderMessage_TerminalInput struct {
	TerminalInput *TerminalInput `protobuf:"bytes,11,opt,name=terminal_input,json=terminalInput,proto3,oneof"` // leader → worker: stdin data
}

type LeaderMessage_TerminalResize struct {
	TerminalResize *TerminalResize `protobuf:"bytes,12,opt,name=terminal_resize,json=terminalResize,proto3,oneof"` // leader → worker: resize PTY
}

type LeaderMessage_CloseTerminal struct {
	CloseTerminal *CloseTerminal `protobuf:"bytes,13,opt,name=close_terminal,json=closeTerminal,proto3,oneof"` // leader → worker: close terminal
}

func (*LeaderMessage_Registered) isLeaderMessage_Msg() {}

func (*LeaderMessage_SpawnWorker) isLeaderMessage_Msg() {}

func (*LeaderMessage_ExecuteTool) isLeaderMessage_Msg() {}

func (*LeaderMessage_ShutdownWorker) isLeaderMessage_Msg() {}

func (*LeaderMessage_KillWorker) isLeaderMessage_Msg() {}

func (*LeaderMessage_FileSync) isLeaderMessage_Msg() {}

func (*LeaderMessage_FileUpdate) isLeaderMessage_Msg() {}

func (*LeaderMessage_Pending) isLeaderMessage_Msg() {}

func (*LeaderMessage_Rejected) isLeaderMessage_Msg() {}

func (*LeaderMessage_CreateTerminal) isLeaderMessage_Msg() {}

func (*LeaderMessage_TerminalInput) isLeaderMessage_Msg() {}

func (*LeaderMessage_TerminalResize) isLeaderMessage_Msg() {}

func (*LeaderMessage_CloseTerminal) isLeaderMessage_Msg() {}

type NodePending struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // identity-derived node ID (hex sha256 of pubkey)
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`             // human-readable reason, e.g. "awaiting approval"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodePending) Reset() {
	*x = NodePending{}
	mi := &file_internal_ipc_proto_hiro_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodePending) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodePending) ProtoMessage() {}

func (x *NodePending) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_proto_hiro_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodePending.ProtoReflect.Descriptor instead.
func (*NodePending) Descriptor() ([]byte, []int) {
	return file_internal_ipc_proto_hiro_proto_rawDescGZIP(), []int{10}
}

func (x *NodePending) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodePending) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type NodeRejected struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // identity-derived node ID
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`               // human-readable reason, e.g. "approval revoked"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeRejected) Reset() {
	*x = NodeRejected{}
	mi := &file_internal_ipc_proto_hiro_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeRejected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeRejected) ProtoMessage() {}

func (x *NodeRejected) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_proto_hiro_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeRejected.ProtoReflect.Descriptor instead.
func (*NodeRejected) Descriptor() ([]byte, []int) {
	return file_internal_ipc_proto_hiro_proto_rawDescGZIP(), []int{11}
}

func (x *NodeRejected) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeRejected) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type NodeRegister struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"` // human-friendly node name
	Capacity      int32                  `protobuf:"varint,3,opt,name=capacity,proto3" json:"capacity,omitempty"`                // max concurrent workers (0 = unlimited)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeRegister) Reset() {
	*x = NodeRegister{}
	mi := &file_internal_ipc_proto_hiro_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeRegister) ProtoMessage() {}

func (x *NodeRegister) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_proto_hiro_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeRegister.ProtoReflect.Descriptor instead.
func (*NodeRegister) Descriptor() ([]byte, []int) {
	return file_internal_ipc_proto_hiro_proto_rawDescGZIP(), []int{12}
}

func (x *NodeRegister) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *NodeRegister) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

type NodeRegistered struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // assigned node ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeRegistered) Reset() {
	*x = NodeRegistered{}
	mi := &file_internal_ipc_proto_hiro_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeRegistered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeRegistered) ProtoMessage() {}

func (x *NodeRegistered) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_proto_hiro_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeRegistered.ProtoReflect.Descriptor instead.
func (*NodeRegistered) Descriptor() ([]byte, []int) {
	return file_internal_ipc_proto_hiro_proto_rawDescGZIP(), []int{13}
}

func (x *NodeRegistered) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type SpawnWorker struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestId      string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // correlates with SpawnResult
	InstanceId     string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	SessionId      string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AgentName      string                 `protobuf:"bytes,4,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	EffectiveTools map[string]bool        `protobuf:"bytes,5,rep,name=effective_tools,json=effectiveTools,proto3" json:"effective_tools,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	WorkingDir     string                 `protobuf:"bytes,6,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"` // relative to node's HIRO_ROOT
	SessionDir     string                 `protobuf:"bytes,7,opt,name=session_dir,json=sessionDir,proto3" json:"session_dir,omitempty"` // relative to node's HIRO_ROOT
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SpawnWorker) Reset() {
	*x = SpawnWorker{}
	mi := &file_internal_ipc_proto_hiro_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpawnWorker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnWorker) ProtoMessage() {}

func (x *SpawnWorker) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_proto_hiro_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnWorker.ProtoReflect.Descriptor instead.
func (*SpawnWorker) Descriptor() ([]byte, []int) {
	return file_internal_ipc_proto_hiro_proto_rawDescGZIP(), []int{14}
}

func (x *SpawnWorker) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SpawnWorker) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *SpawnWorker) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SpawnWorker) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *SpawnWorker) GetEffectiveTools() map[string]bool {
	if x != nil {
		return x.EffectiveTools
	}
	return nil
}

func (x *SpawnWorker) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *SpawnWorker) GetSessionDir() string {
	if x != nil {
		return x.SessionDir
	}
	return ""
}

type SpawnResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // correlates with SpawnWorker
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`                          // empty on success
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpawnResult) Reset() {
	*x = SpawnResult{}
	mi := &file_internal_ipc_proto_hiro_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpawnResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnResult) ProtoMessage() {}

func (x *SpawnResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_proto_hiro_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnResult.ProtoReflect.Descriptor instead.
func (*SpawnResult) Descriptor() ([]byte, []int) {
	return file_internal_ipc_proto_hiro_proto_rawDescGZIP(), []int{15}
}

func (x *SpawnResult) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SpawnResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ShutdownWorker struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // identifies which worker to shutdown
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownWorker) Reset() {
	*x = ShutdownWorker{}
	mi := &file_internal_ipc_proto_hiro_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownWorker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownWorker) ProtoMessage() {}

func (x *ShutdownWorker) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_proto_hiro_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownWorker.ProtoReflect.Descriptor instead.
func (*ShutdownWorker) Descriptor() ([]byte, []int) {
	return file_internal_ipc_proto_hiro_proto_rawDescGZIP(), []int{16}
}

func (x *ShutdownWorker) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type KillWorker struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // identifies which worker to kill
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillWorker) Reset() {
	*x = KillWorker{}
	mi := &file_internal_ipc_proto_hiro_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillWorker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillWorker) ProtoMessage() {}

func (x *KillWorker) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_proto_hiro_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillWorker.ProtoReflect.Descriptor instead.
func (*KillWorker) Descriptor() ([]byte, []int) {
	return file_internal_ipc_proto_hiro_proto_rawDescGZIP(), []int{17}
}

func (x *KillWorker) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type WorkerExited struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // worker that exited
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`                          // non-empty if unexpected exit
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerExited) Reset() {
	*x = WorkerExited{}
	mi := &file_internal_ipc_proto_hiro_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerExited) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerExited) ProtoMessage() {}

func (x *WorkerExited) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_proto_hiro_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerExited.ProtoReflect.Descriptor instead.
func (*WorkerExited) Descriptor() ([]byte, []int) {
	return file_internal_ipc_proto_hiro_proto_rawDescGZIP(), []int{18}
}

func (x *WorkerExited) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *WorkerExited) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ExecuteToolRemote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // identifies which worker to use
	CallId        string                 `protobuf:"bytes,2,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	ToolName      string                 `protobuf:"bytes,3,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	Input         string                 `protobuf:"bytes,4,opt,name=input,proto3" json:"input,omitempty"`                          // JSON-encoded tool arguments
	SecretEnv     []string               `protobuf:"bytes,5,rep,name=secret_env,json=secretEnv,proto3" json:"secret_env,omitempty"` // secret env vars for bash
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteToolRemote) Reset() {
	*x = ExecuteToolRemote{}
	mi := &file_internal_ipc_proto_hiro_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteToolRemote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteToolRemote) ProtoMessage() {}

func (x *ExecuteToolRemote) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_proto_hiro_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteToolRemote.ProtoReflect.Descriptor instead.
func (*ExecuteToolRemote) Descriptor() ([]byte, []int) {
	return file_internal_ipc_proto_hiro_proto_rawDescGZIP(), []int{19}
}

func (x *ExecuteToolRemote) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ExecuteToolRemote) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *ExecuteToolRemote) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ExecuteToolRemote) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *ExecuteToolRemote) GetSecretEnv() []string {
	if x != nil {
		return x.SecretEnv
	}
	return nil
}

type NodeToolResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	IsError       bool                   `protobuf:"varint,3,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`                          // transport-level error (distinct from tool error)
	SessionId     string                 `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // which worker this result belongs to
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeToolResult) Reset() {
	*x = NodeToolResult{}
	mi := &file_internal_ipc_proto_hiro_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeToolResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeToolResult) ProtoMessage() {}

func (x *NodeToolResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_proto_hiro_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeToolResult.ProtoReflect.Descriptor instead.
func (*NodeToolResult) Descriptor() ([]byte, []int) {
	return file_internal_ipc_proto_hiro_proto_rawDescGZIP(), []int{20}
}

func (x *NodeToolResult) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *NodeToolResult) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *NodeToolResult) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

func (x *NodeToolResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *NodeToolResult) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type NodeHeartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActiveWorkers int32                  `protobuf:"varint,1,opt,name=active_workers,json=activeWorkers,proto3" json:"active_workers,omitempty"` // current count for leader tracking
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeHeartbeat) Reset() {
	*x = NodeHeartbeat{}
	mi := &file_internal_ipc_proto_hiro_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeHeartbeat) ProtoMessage() {}

func (x *NodeHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_proto_hiro_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeHeartbeat.ProtoReflect.Descriptor instead.
func (*NodeHeartbeat) Descriptor() ([]byte, []int) {
	return file_internal_ipc_proto_hiro_proto_rawDescGZIP(), []int{21}
}

func (x *NodeHeartbeat) GetActiveWorkers() int32 {
	if x != nil {
		return x.ActiveWorkers
	}
	return 0
}

type FileSyncData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`    // tar.gz chunk
	Final         bool                   `protobuf:"varint,2,opt,name=final,proto3" json:"final,omitempty"` // true for the last chunk
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileSyncData) Reset() {
	*x = FileSyncData{}
	mi := &file_internal_ipc_proto_hiro_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileSyncData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileSyncData) ProtoMessage() {}

func (x *FileSyncData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_proto_hiro_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileSyncData.ProtoReflect.Descriptor instead.
func (*FileSyncData) Descriptor() ([]byte, []int) {
	return file_internal_ipc_proto_hiro_proto_rawDescGZIP(), []int{22}
}

func (x *FileSyncData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FileSyncData) GetFinal() bool {
	if x != nil {
		return x.Final
	}
	return false
}

type FileUpdate struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Path           string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`                                              // relative path within HIRO_ROOT
	Content        []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`                                        // file content (empty for deletion)
	Deleted        bool                   `protobuf:"varint,3,opt,name=deleted,proto3" json:"deleted,omitempty"`                                       // true if file was deleted
	Mode           uint32                 `protobuf:"varint,4,opt,name=mode,proto3" json:"mode,omitempty"`                                             // file permission bits (e.g., 0644)
	MtimeUnixNanos int64                  `protobuf:"varint,5,opt,name=mtime_unix_nanos,json=mtimeUnixNanos,proto3" json:"mtime_unix_nanos,omitempty"` // modification time for conflict detection
	OriginNode     string                 `protobuf:"bytes,6,opt,name=origin_node,json=originNode,proto3" json:"origin_node,omitempty"`                // which node made this change (for conflict files)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FileUpdate) Reset() {
	*x = FileUpdate{}
	mi := &file_internal_ipc_proto_hiro_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUpdate) ProtoMessage() {}

func (x *FileUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_proto_hiro_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUpdate.ProtoReflect.Descriptor instead.
func (*FileUpdate) Descriptor() ([]byte, []int) {
	return file_internal_ipc_proto_hiro_proto_rawDescGZIP(), []int{23}
}

func (x *FileUpdate) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileUpdate) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *FileUpdate) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *FileUpdate) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *FileUpdate) GetMtimeUnixNanos() int64 {
	if x != nil {
		return x.MtimeUnixNanos
	}
	return 0
}

func (x *FileUpdate) GetOriginNode() string {
	if x != nil {
		return x.OriginNode
	}
	return ""
}

type CreateTerminal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // assigned by leader
	Cols          uint32                 `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,3,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTerminal) Reset() {
	*x = CreateTerminal{}
	mi := &file_internal_ipc_proto_hiro_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTerminal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTerminal) ProtoMessage() {}

func (x *CreateTerminal) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_proto_hiro_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTerminal.ProtoReflect.Descriptor instead.
func (*CreateTerminal) Descriptor() ([]byte, []int) {
	return file_internal_ipc_proto_hiro_proto_rawDescGZIP(), []int{24}
}

func (x *CreateTerminal) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreateTerminal) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *CreateTerminal) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type TerminalCreated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // non-empty on failure
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalCreated) Reset() {
	*x = TerminalCreated{}
	mi := &file_internal_ipc_proto_hiro_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalCreated) ProtoMessage() {}

func (x *TerminalCreated) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_proto_hiro_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalCreated.ProtoReflect.Descriptor instead.
func (*TerminalCreated) Descriptor() ([]byte, []int) {
	return file_internal_ipc_proto_hiro_proto_rawDescGZIP(), []int{25}
}

func (x *TerminalCreated) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TerminalCreated) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type TerminalInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"` // stdin bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalInput) Reset() {
	*x = TerminalInput{}
	mi := &file_internal_ipc_proto_hiro_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalInput) ProtoMessage() {}

func (x *TerminalInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_proto_hiro_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalInput.ProtoReflect.Descriptor instead.
func (*TerminalInput) Descriptor() ([]byte, []int) {
	return file_internal_ipc_proto_hiro_proto_rawDescGZIP(), []int{26}
}

func (x *TerminalInput) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TerminalInput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type TerminalOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"` // stdout/stderr bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalOutput) Reset() {
	*x = TerminalOutput{}
	mi := &file_internal_ipc_proto_hiro_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalOutput) ProtoMessage() {}

func (x *TerminalOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_proto_hiro_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalOutput.ProtoReflect.Descriptor instead.
func (*TerminalOutput) Descriptor() ([]byte, []int) {
	return file_internal_ipc_proto_hiro_proto_rawDescGZIP(), []int{27}
}

func (x *TerminalOutput) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TerminalOutput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type TerminalResize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Cols          uint32                 `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,3,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalResize) Reset() {
	*x = TerminalResize{}
	mi := &file_internal_ipc_proto_hiro_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalResize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalResize) ProtoMessage() {}

func (x *TerminalResize) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_proto_hiro_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalResize.ProtoReflect.Descriptor instead.
func (*TerminalResize) Descriptor() ([]byte, []int) {
	return file_internal_ipc_proto_hiro_proto_rawDescGZIP(), []int{28}
}

func (x *TerminalResize) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TerminalResize) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *TerminalResize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type CloseTerminal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseTerminal) Reset() {
	*x = CloseTerminal{}
	mi := &file_internal_ipc_proto_hiro_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseTerminal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseTerminal) ProtoMessage() {}

func (x *CloseTerminal) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_proto_hiro_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseTerminal.ProtoReflect.Descriptor instead.
func (*CloseTerminal) Descriptor() ([]byte, []int) {
	return file_internal_ipc_proto_hiro_proto_rawDescGZIP(), []int{29}
}

func (x *CloseTerminal) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type TerminalExited struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ExitCode      int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalExited) Reset() {
	*x = TerminalExited{}
	mi := &file_internal_ipc_proto_hiro_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalExited) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalExited) ProtoMessage() {}

func (x *TerminalExited) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_proto_hiro_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalExited.ProtoReflect.Descriptor instead.
func (*TerminalExited) Descriptor() ([]byte, []int) {
	return file_internal_ipc_proto_hiro_proto_rawDescGZIP(), []int{30}
}

func (x *TerminalExited) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TerminalExited) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

var File_internal_ipc_proto_hiro_proto protoreflect.FileDescriptor

const file_internal_ipc_proto_hiro_proto_rawDesc = "" +
	"\n" +
	"\x1dinternal/ipc/proto/hiro.proto\x12\x04hiro\"\x12\n" +
	"\x10WatchJobsRequest\"\x99\x01\n" +
	"\rJobCompletion\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06failed\x18\x05 \x01(\bR\x06failed\"v\n" +
	"\x12ExecuteToolRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05input\x18\x02 \x01(\tR\x05input\x12\x17\n" +
	"\acall_id\x18\x03 \x01(\tR\x06callId\x12\x1d\n" +
	"\n" +
	"secret_env\x18\x04 \x03(\tR\tsecretEnv\"J\n" +
	"\x13ExecuteToolResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x19\n" +
	"\bis_error\x18\x02 \x01(\bR\aisError\"\x11\n" +
	"\x0fShutdownRequest\"\x12\n" +
	"\x10ShutdownResponse\"\x9f\x05\n" +
	"\vNodeMessage\x120\n" +
	"\bregister\x18\x01 \x01(\v2\x12.hiro.NodeRegisterH\x00R\bregister\x126\n" +
	"\fspawn_result\x18\x02 \x01(\v2\x11.hiro.SpawnResultH\x00R\vspawnResult\x127\n" +
	"\vtool_result\x18\x03 \x01(\v2\x14.hiro.NodeToolResultH\x00R\n" +
	"toolResult\x123\n" +
	"\theartbeat\x18\x04 \x01(\v2\x13.hiro.NodeHeartbeatH\x00R\theartbeat\x129\n" +
	"\rworker_exited\x18\x05 \x01(\v2\x12.hiro.WorkerExitedH\x00R\fworkerExited\x123\n" +
	"\vfile_update\x18\x06 \x01(\v2\x10.hiro.FileUpdateH\x00R\n" +
	"fileUpdate\x127\n" +
	"\rfile_sync_ack\x18\a \x01(\v2\x11.hiro.FileSyncAckH\x00R\vfileSyncAck\x12B\n" +
	"\x0ejob_completion\x18\b \x01(\v2\x19.hiro.JobCompletionNotifyH\x00R\rjobCompletion\x12B\n" +
	"\x10terminal_created\x18\t \x01(\v2\x15.hiro.TerminalCreatedH\x00R\x0fterminalCreated\x12?\n" +
	"\x0fterminal_output\x18\n" +
	" \x01(\v2\x14.hiro.TerminalOutputH\x00R\x0eterminalOutput\x12?\n" +
	"\x0fterminal_exited\x18\v \x01(\v2\x14.hiro.TerminalExitedH\x00R\x0eterminalExitedB\x05\n" +
	"\x03msg\"\xbe\x01\n" +
	"\x13JobCompletionNotify\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\texit_code\x18\x05 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06failed\x18\x06 \x01(\bR\x06failed\"\r\n" +
	"\vFileSyncAck\"\x81\x06\n" +
	"\rLeaderMessage\x126\n" +
	"\n" +
	"registered\x18\x01 \x01(\v2\x14.hiro.NodeRegisteredH\x00R\n" +
	"registered\x126\n" +
	"\fspawn_worker\x18\x02 \x01(\v2\x11.hiro.SpawnWorkerH\x00R\vspawnWorker\x12<\n" +
	"\fexecute_tool\x18\x03 \x01(\v2\x17.hiro.ExecuteToolRemoteH\x00R\vexecuteTool\x12?\n" +
	"\x0fshutdown_worker\x18\x04 \x01(\v2\x14.hiro.ShutdownWorkerH\x00R\x0eshutdownWorker\x123\n" +
	"\vkill_worker\x18\x05 \x01(\v2\x10.hiro.KillWorkerH\x00R\n" +
	"killWorker\x121\n" +
	"\tfile_sync\x18\x06 \x01(\v2\x12.hiro.FileSyncDataH\x00R\bfileSync\x123\n" +
	"\vfile_update\x18\a \x01(\v2\x10.hiro.FileUpdateH\x00R\n" +
	"fileUpdate\x12-\n" +
	"\apending\x18\b \x01(\v2\x11.hiro.NodePendingH\x00R\apending\x120\n" +
	"\brejected\x18\t \x01(\v2\x12.hiro.NodeRejectedH\x00R\brejected\x12?\n" +
	"\x0fcreate_terminal\x18\n" +
	" \x01(\v2\x14.hiro.CreateTerminalH\x00R\x0ecreateTerminal\x12<\n" +
	"\x0eterminal_input\x18\v \x01(\v2\x13.hiro.TerminalInputH\x00R\rterminalInput\x12?\n" +
	"\x0fterminal_resize\x18\f \x01(\v2\x14.hiro.TerminalResizeH\x00R\x0eterminalResize\x12<\n" +
	"\x0eclose_terminal\x18\r \x01(\v2\x13.hiro.CloseTerminalH\x00R\rcloseTerminalB\x05\n" +
	"\x03msg\"@\n" +
	"\vNodePending\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"?\n" +
	"\fNodeRejected\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"M\n" +
	"\fNodeRegister\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12\x1a\n" +
	"\bcapacity\x18\x03 \x01(\x05R\bcapacityJ\x04\b\x02\x10\x03\")\n" +
	"\x0eNodeRegistered\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"\xe0\x02\n" +
	"\vSpawnWorker\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x04 \x01(\tR\tagentName\x12N\n" +
	"\x0feffective_tools\x18\x05 \x03(\v2%.hiro.SpawnWorker.EffectiveToolsEntryR\x0eeffectiveTools\x12\x1f\n" +
	"\vworking_dir\x18\x06 \x01(\tR\n" +
	"workingDir\x12\x1f\n" +
	"\vsession_dir\x18\a \x01(\tR\n" +
	"sessionDir\x1aA\n" +
	"\x13EffectiveToolsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"B\n" +
	"\vSpawnResult\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"/\n" +
	"\x0eShutdownWorker\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"+\n" +
	"\n" +
	"KillWorker\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"C\n" +
	"\fWorkerExited\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x9d\x01\n" +
	"\x11ExecuteToolRemote\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\acall_id\x18\x02 \x01(\tR\x06callId\x12\x1b\n" +
	"\ttool_name\x18\x03 \x01(\tR\btoolName\x12\x14\n" +
	"\x05input\x18\x04 \x01(\tR\x05input\x12\x1d\n" +
	"\n" +
	"secret_env\x18\x05 \x03(\tR\tsecretEnv\"\x93\x01\n" +
	"\x0eNodeToolResult\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x19\n" +
	"\bis_error\x18\x03 \x01(\bR\aisError\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\"6\n" +
	"\rNodeHeartbeat\x12%\n" +
	"\x0eactive_workers\x18\x01 \x01(\x05R\ractiveWorkers\"8\n" +
	"\fFileSyncData\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x14\n" +
	"\x05final\x18\x02 \x01(\bR\x05final\"\xb3\x01\n" +
	"\n" +
	"FileUpdate\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12\x18\n" +
	"\adeleted\x18\x03 \x01(\bR\adeleted\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\rR\x04mode\x12(\n" +
	"\x10mtime_unix_nanos\x18\x05 \x01(\x03R\x0emtimeUnixNanos\x12\x1f\n" +
	"\vorigin_node\x18\x06 \x01(\tR\n" +
	"originNode\"W\n" +
	"\x0eCreateTerminal\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x03 \x01(\rR\x04rows\"F\n" +
	"\x0fTerminalCreated\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"B\n" +
	"\rTerminalInput\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"C\n" +
	"\x0eTerminalOutput\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"W\n" +
	"\x0eTerminalResize\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x03 \x01(\rR\x04rows\".\n" +
	"\rCloseTerminal\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"L\n" +
	"\x0eTerminalExited\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode2\xc8\x01\n" +
	"\vAgentWorker\x12B\n" +
	"\vExecuteTool\x12\x18.hiro.ExecuteToolRequest\x1a\x19.hiro.ExecuteToolResponse\x129\n" +
	"\bShutdown\x12\x15.hiro.ShutdownRequest\x1a\x16.hiro.ShutdownResponse\x12:\n" +
	"\tWatchJobs\x12\x16.hiro.WatchJobsRequest\x1a\x13.hiro.JobCompletion0\x012C\n" +
	"\aCluster\x128\n" +
	"\n" +
	"NodeStream\x12\x11.hiro.NodeMessage\x1a\x13.hiro.LeaderMessage(\x010\x01B-Z+github.com/nchapman/hiro/internal/ipc/protob\x06proto3"

var (
	file_internal_ipc_proto_hiro_proto_rawDescOnce sync.Once
	file_internal_ipc_proto_hiro_proto_rawDescData []byte
)

func file_internal_ipc_proto_hiro_proto_rawDescGZIP() []byte {
	file_internal_ipc_proto_hiro_proto_rawDescOnce.Do(func() {
		file_internal_ipc_proto_hiro_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_ipc_proto_hiro_proto_rawDesc), len(file_internal_ipc_proto_hiro_proto_rawDesc)))
	})
	return file_internal_ipc_proto_hiro_proto_rawDescData
}

var file_internal_ipc_proto_hiro_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_internal_ipc_proto_hiro_proto_goTypes = []any{
	(*WatchJobsRequest)(nil),    // 0: hiro.WatchJobsRequest
	(*JobCompletion)(nil),       // 1: hiro.JobCompletion
	(*ExecuteToolRequest)(nil),  // 2: hiro.ExecuteToolRequest
	(*ExecuteToolResponse)(nil), // 3: hiro.ExecuteToolResponse
	(*ShutdownRequest)(nil),     // 4: hiro.ShutdownRequest
	(*ShutdownResponse)(nil),    // 5: hiro.ShutdownResponse
	(*NodeMessage)(nil),         // 6: hiro.NodeMessage
	(*JobCompletionNotify)(nil), // 7: hiro.JobCompletionNotify
	(*FileSyncAck)(nil),         // 8: hiro.FileSyncAck
	(*LeaderMessage)(nil),       // 9: hiro.LeaderMessage
	(*NodePending)(nil),         // 10: hiro.NodePending
	(*NodeRejected)(nil),        // 11: hiro.NodeRejected
	(*NodeRegister)(nil),        // 12: hiro.NodeRegister
	(*NodeRegistered)(nil),      // 13: hiro.NodeRegistered
	(*SpawnWorker)(nil),         // 14: hiro.SpawnWorker
	(*SpawnResult)(nil),         // 15: hiro.SpawnResult
	(*ShutdownWorker)(nil),      // 16: hiro.ShutdownWorker
	(*KillWorker)(nil),          // 17: hiro.KillWorker
	(*WorkerExited)(nil),        // 18: hiro.WorkerExited
	(*ExecuteToolRemote)(nil),   // 19: hiro.ExecuteToolRemote
	(*NodeToolResult)(nil),      // 20: hiro.NodeToolResult
	(*NodeHeartbeat)(nil),       // 21: hiro.NodeHeartbeat
	(*FileSyncData)(nil),        // 22: hiro.FileSyncData
	(*FileUpdate)(nil),          // 23: hiro.FileUpdate
	(*CreateTerminal)(nil),      // 24: hiro.CreateTerminal
	(*TerminalCreated)(nil),     // 25: hiro.TerminalCreated
	(*TerminalInput)(nil),       // 26: hiro.TerminalInput
	(*TerminalOutput)(nil),      // 27: hiro.TerminalOutput
	(*TerminalResize)(nil),      // 28: hiro.TerminalResize
	(*CloseTerminal)(nil),       // 29: hiro.CloseTerminal
	(*TerminalExited)(nil),      // 30: hiro.TerminalExited
	nil,                         // 31: hiro.SpawnWorker.EffectiveToolsEntry
}
var file_internal_ipc_proto_hiro_proto_depIdxs = []int32{
	12, // 0: hiro.NodeMessage.register:type_name -> hiro.NodeRegister
	15, // 1: hiro.NodeMessage.spawn_result:type_name -> hiro.SpawnResult
	20, // 2: hiro.NodeMessage.tool_result:type_name -> hiro.NodeToolResult
	21, // 3: hiro.NodeMessage.heartbeat:type_name -> hiro.NodeHeartbeat
	18, // 4: hiro.NodeMessage.worker_exited:type_name -> hiro.WorkerExited
	23, // 5: hiro.NodeMessage.file_update:type_name -> hiro.FileUpdate
	8,  // 6: hiro.NodeMessage.file_sync_ack:type_name -> hiro.FileSyncAck
	7,  // 7: hiro.NodeMessage.job_completion:type_name -> hiro.JobCompletionNotify
	25, // 8: hiro.NodeMessage.terminal_created:type_name -> hiro.TerminalCreated
	27, // 9: hiro.NodeMessage.terminal_output:type_name -> hiro.TerminalOutput
	30, // 10: hiro.NodeMessage.terminal_exited:type_name -> hiro.TerminalExited
	13, // 11: hiro.LeaderMessage.registered:type_name -> hiro.NodeRegistered
	14, // 12: hiro.LeaderMessage.spawn_worker:type_name -> hiro.SpawnWorker
	19, // 13: hiro.LeaderMessage.execute_tool:type_name -> hiro.ExecuteToolRemote
	16, // 14: hiro.LeaderMessage.shutdown_worker:type_name -> hiro.ShutdownWorker
	17, // 15: hiro.LeaderMessage.kill_worker:type_name -> hiro.KillWorker
	22, // 16: hiro.LeaderMessage.file_sync:type_name -> hiro.FileSyncData
	23, // 17: hiro.LeaderMessage.file_update:type_name -> hiro.FileUpdate
	10, // 18: hiro.LeaderMessage.pending:type_name -> hiro.NodePending
	11, // 19: hiro.LeaderMessage.rejected:type_name -> hiro.NodeRejected
	24, // 20: hiro.LeaderMessage.create_terminal:type_name -> hiro.CreateTerminal
	26, // 21: hiro.LeaderMessage.terminal_input:type_name -> hiro.TerminalInput
	28, // 22: hiro.LeaderMessage.terminal_resize:type_name -> hiro.TerminalResize
	29, // 23: hiro.LeaderMessage.close_terminal:type_name -> hiro.CloseTerminal
	31, // 24: hiro.SpawnWorker.effective_tools:type_name -> hiro.SpawnWorker.EffectiveToolsEntry
	2,  // 25: hiro.AgentWorker.ExecuteTool:input_type -> hiro.ExecuteToolRequest
	4,  // 26: hiro.AgentWorker.Shutdown:input_type -> hiro.ShutdownRequest
	0,  // 27: hiro.AgentWorker.WatchJobs:input_type -> hiro.WatchJobsRequest
	6,  // 28: hiro.Cluster.NodeStream:input_type -> hiro.NodeMessage
	3,  // 29: hiro.AgentWorker.ExecuteTool:output_type -> hiro.ExecuteToolResponse
	5,  // 30: hiro.AgentWorker.Shutdown:output_type -> hiro.ShutdownResponse
	1,  // 31: hiro.AgentWorker.WatchJobs:output_type -> hiro.JobCompletion
	9,  // 32: hiro.Cluster.NodeStream:output_type -> hiro.LeaderMessage
	29, // [29:33] is the sub-list for method output_type
	25, // [25:29] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_internal_ipc_proto_hiro_proto_init() }
func file_internal_ipc_proto_hiro_proto_init() {
	if File_internal_ipc_proto_hiro_proto != nil {
		return
	}
	file_internal_ipc_proto_hiro_proto_msgTypes[6].OneofWrappers = []any{
		(*NodeMessage_Register)(nil),
		(*NodeMessage_SpawnResult)(nil),
		(*NodeMessage_ToolResult)(nil),
		(*NodeMessage_Heartbeat)(nil),
		(*NodeMessage_WorkerExited)(nil),
		(*NodeMessage_FileUpdate)(nil),
		(*NodeMessage_FileSyncAck)(nil),
		(*NodeMessage_JobCompletion)(nil),
		(*NodeMessage_TerminalCreated)(nil),
		(*NodeMessage_TerminalOutput)(nil),
		(*NodeMessage_TerminalExited)(nil),
	}
	file_internal_ipc_proto_hiro_proto_msgTypes[9].OneofWrappers = []any{
		(*LeaderMessage_Registered)(nil),
		(*LeaderMessage_SpawnWorker)(nil),
		(*LeaderMessage_ExecuteTool)(nil),
		(*LeaderMessage_ShutdownWorker)(nil),
		(*LeaderMessage_KillWorker)(nil),
		(*LeaderMessage_FileSync)(nil),
		(*LeaderMessage_FileUpdate)(nil),
		(*LeaderMessage_Pending)(nil),
		(*LeaderMessage_Rejected)(nil),
		(*LeaderMessage_CreateTerminal)(nil),
		(*LeaderMessage_TerminalInput)(nil),
		(*LeaderMessage_TerminalResize)(nil),
		(*LeaderMessage_CloseTerminal)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_ipc_proto_hiro_proto_rawDesc), len(file_internal_ipc_proto_hiro_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_internal_ipc_proto_hiro_proto_goTypes,
		DependencyIndexes: file_internal_ipc_proto_hiro_proto_depIdxs,
		MessageInfos:      file_internal_ipc_proto_hiro_proto_msgTypes,
	}.Build()
	File_internal_ipc_proto_hiro_proto = out.File
	file_internal_ipc_proto_hiro_proto_goTypes = nil
	file_internal_ipc_proto_hiro_proto_depIdxs = nil
}
