// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: internal/ipc/proto/hive.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentWorker_ExecuteTool_FullMethodName = "/hive.AgentWorker/ExecuteTool"
	AgentWorker_Shutdown_FullMethodName    = "/hive.AgentWorker/Shutdown"
)

// AgentWorkerClient is the client API for AgentWorker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentWorker is served by each agent worker process. The control plane
// calls these RPCs to execute tools and manage the worker's lifecycle.
type AgentWorkerClient interface {
	// ExecuteTool runs a single tool in the worker's sandbox and returns the result.
	ExecuteTool(ctx context.Context, in *ExecuteToolRequest, opts ...grpc.CallOption) (*ExecuteToolResponse, error)
	// Shutdown gracefully stops the agent worker process.
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error)
}

type agentWorkerClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentWorkerClient(cc grpc.ClientConnInterface) AgentWorkerClient {
	return &agentWorkerClient{cc}
}

func (c *agentWorkerClient) ExecuteTool(ctx context.Context, in *ExecuteToolRequest, opts ...grpc.CallOption) (*ExecuteToolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteToolResponse)
	err := c.cc.Invoke(ctx, AgentWorker_ExecuteTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentWorkerClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShutdownResponse)
	err := c.cc.Invoke(ctx, AgentWorker_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentWorkerServer is the server API for AgentWorker service.
// All implementations must embed UnimplementedAgentWorkerServer
// for forward compatibility.
//
// AgentWorker is served by each agent worker process. The control plane
// calls these RPCs to execute tools and manage the worker's lifecycle.
type AgentWorkerServer interface {
	// ExecuteTool runs a single tool in the worker's sandbox and returns the result.
	ExecuteTool(context.Context, *ExecuteToolRequest) (*ExecuteToolResponse, error)
	// Shutdown gracefully stops the agent worker process.
	Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error)
	mustEmbedUnimplementedAgentWorkerServer()
}

// UnimplementedAgentWorkerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentWorkerServer struct{}

func (UnimplementedAgentWorkerServer) ExecuteTool(context.Context, *ExecuteToolRequest) (*ExecuteToolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteTool not implemented")
}
func (UnimplementedAgentWorkerServer) Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedAgentWorkerServer) mustEmbedUnimplementedAgentWorkerServer() {}
func (UnimplementedAgentWorkerServer) testEmbeddedByValue()                     {}

// UnsafeAgentWorkerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentWorkerServer will
// result in compilation errors.
type UnsafeAgentWorkerServer interface {
	mustEmbedUnimplementedAgentWorkerServer()
}

func RegisterAgentWorkerServer(s grpc.ServiceRegistrar, srv AgentWorkerServer) {
	// If the following call panics, it indicates UnimplementedAgentWorkerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentWorker_ServiceDesc, srv)
}

func _AgentWorker_ExecuteTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentWorkerServer).ExecuteTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentWorker_ExecuteTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentWorkerServer).ExecuteTool(ctx, req.(*ExecuteToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentWorker_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentWorkerServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentWorker_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentWorkerServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentWorker_ServiceDesc is the grpc.ServiceDesc for AgentWorker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentWorker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hive.AgentWorker",
	HandlerType: (*AgentWorkerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteTool",
			Handler:    _AgentWorker_ExecuteTool_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _AgentWorker_Shutdown_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/ipc/proto/hive.proto",
}
