// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: internal/ipc/proto/hive.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ChatEvent is a streaming event sent during Chat, SpawnAgent, or SendMessage.
type ChatEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// type is "delta" for incremental text, "done" for final result, or "error".
	Type          string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Content       string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatEvent) Reset() {
	*x = ChatEvent{}
	mi := &file_internal_ipc_proto_hive_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatEvent) ProtoMessage() {}

func (x *ChatEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_proto_hive_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatEvent.ProtoReflect.Descriptor instead.
func (*ChatEvent) Descriptor() ([]byte, []int) {
	return file_internal_ipc_proto_hive_proto_rawDescGZIP(), []int{0}
}

func (x *ChatEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ChatEvent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type SpawnAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentName     string                 `protobuf:"bytes,1,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	Prompt        string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	ParentId      string                 `protobuf:"bytes,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpawnAgentRequest) Reset() {
	*x = SpawnAgentRequest{}
	mi := &file_internal_ipc_proto_hive_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpawnAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnAgentRequest) ProtoMessage() {}

func (x *SpawnAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_proto_hive_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnAgentRequest.ProtoReflect.Descriptor instead.
func (*SpawnAgentRequest) Descriptor() ([]byte, []int) {
	return file_internal_ipc_proto_hive_proto_rawDescGZIP(), []int{1}
}

func (x *SpawnAgentRequest) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *SpawnAgentRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *SpawnAgentRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

type StartAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentName     string                 `protobuf:"bytes,1,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	ParentId      string                 `protobuf:"bytes,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartAgentRequest) Reset() {
	*x = StartAgentRequest{}
	mi := &file_internal_ipc_proto_hive_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartAgentRequest) ProtoMessage() {}

func (x *StartAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_proto_hive_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartAgentRequest.ProtoReflect.Descriptor instead.
func (*StartAgentRequest) Descriptor() ([]byte, []int) {
	return file_internal_ipc_proto_hive_proto_rawDescGZIP(), []int{2}
}

func (x *StartAgentRequest) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *StartAgentRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

type StartAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartAgentResponse) Reset() {
	*x = StartAgentResponse{}
	mi := &file_internal_ipc_proto_hive_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartAgentResponse) ProtoMessage() {}

func (x *StartAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_proto_hive_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartAgentResponse.ProtoReflect.Descriptor instead.
func (*StartAgentResponse) Descriptor() ([]byte, []int) {
	return file_internal_ipc_proto_hive_proto_rawDescGZIP(), []int{3}
}

func (x *StartAgentResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	CallerId      string                 `protobuf:"bytes,3,opt,name=caller_id,json=callerId,proto3" json:"caller_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_internal_ipc_proto_hive_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_proto_hive_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_internal_ipc_proto_hive_proto_rawDescGZIP(), []int{4}
}

func (x *SendMessageRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *SendMessageRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendMessageRequest) GetCallerId() string {
	if x != nil {
		return x.CallerId
	}
	return ""
}

type StopAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	CallerId      string                 `protobuf:"bytes,2,opt,name=caller_id,json=callerId,proto3" json:"caller_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopAgentRequest) Reset() {
	*x = StopAgentRequest{}
	mi := &file_internal_ipc_proto_hive_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopAgentRequest) ProtoMessage() {}

func (x *StopAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_proto_hive_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopAgentRequest.ProtoReflect.Descriptor instead.
func (*StopAgentRequest) Descriptor() ([]byte, []int) {
	return file_internal_ipc_proto_hive_proto_rawDescGZIP(), []int{5}
}

func (x *StopAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *StopAgentRequest) GetCallerId() string {
	if x != nil {
		return x.CallerId
	}
	return ""
}

type StopAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopAgentResponse) Reset() {
	*x = StopAgentResponse{}
	mi := &file_internal_ipc_proto_hive_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopAgentResponse) ProtoMessage() {}

func (x *StopAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_proto_hive_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopAgentResponse.ProtoReflect.Descriptor instead.
func (*StopAgentResponse) Descriptor() ([]byte, []int) {
	return file_internal_ipc_proto_hive_proto_rawDescGZIP(), []int{6}
}

type ListAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentId      string                 `protobuf:"bytes,1,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
	mi := &file_internal_ipc_proto_hive_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_proto_hive_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest) Descriptor() ([]byte, []int) {
	return file_internal_ipc_proto_hive_proto_rawDescGZIP(), []int{7}
}

func (x *ListAgentsRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

type ListAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*AgentInfoProto      `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	mi := &file_internal_ipc_proto_hive_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_proto_hive_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_internal_ipc_proto_hive_proto_rawDescGZIP(), []int{8}
}

func (x *ListAgentsResponse) GetAgents() []*AgentInfoProto {
	if x != nil {
		return x.Agents
	}
	return nil
}

type AgentInfoProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Mode          string                 `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ParentId      string                 `protobuf:"bytes,5,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentInfoProto) Reset() {
	*x = AgentInfoProto{}
	mi := &file_internal_ipc_proto_hive_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInfoProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfoProto) ProtoMessage() {}

func (x *AgentInfoProto) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_proto_hive_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfoProto.ProtoReflect.Descriptor instead.
func (*AgentInfoProto) Descriptor() ([]byte, []int) {
	return file_internal_ipc_proto_hive_proto_rawDescGZIP(), []int{9}
}

func (x *AgentInfoProto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AgentInfoProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentInfoProto) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *AgentInfoProto) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AgentInfoProto) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

type GetSecretsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretsRequest) Reset() {
	*x = GetSecretsRequest{}
	mi := &file_internal_ipc_proto_hive_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretsRequest) ProtoMessage() {}

func (x *GetSecretsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_proto_hive_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretsRequest.ProtoReflect.Descriptor instead.
func (*GetSecretsRequest) Descriptor() ([]byte, []int) {
	return file_internal_ipc_proto_hive_proto_rawDescGZIP(), []int{10}
}

type GetSecretsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Names         []string               `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	Env           []string               `protobuf:"bytes,2,rep,name=env,proto3" json:"env,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretsResponse) Reset() {
	*x = GetSecretsResponse{}
	mi := &file_internal_ipc_proto_hive_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretsResponse) ProtoMessage() {}

func (x *GetSecretsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_proto_hive_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretsResponse.ProtoReflect.Descriptor instead.
func (*GetSecretsResponse) Descriptor() ([]byte, []int) {
	return file_internal_ipc_proto_hive_proto_rawDescGZIP(), []int{11}
}

func (x *GetSecretsResponse) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

func (x *GetSecretsResponse) GetEnv() []string {
	if x != nil {
		return x.Env
	}
	return nil
}

type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_internal_ipc_proto_hive_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_proto_hive_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_internal_ipc_proto_hive_proto_rawDescGZIP(), []int{12}
}

func (x *ChatRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_internal_ipc_proto_hive_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_proto_hive_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_internal_ipc_proto_hive_proto_rawDescGZIP(), []int{13}
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_internal_ipc_proto_hive_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_proto_hive_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_internal_ipc_proto_hive_proto_rawDescGZIP(), []int{14}
}

var File_internal_ipc_proto_hive_proto protoreflect.FileDescriptor

const file_internal_ipc_proto_hive_proto_rawDesc = "" +
	"\n" +
	"\x1dinternal/ipc/proto/hive.proto\x12\x04hive\"9\n" +
	"\tChatEvent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"g\n" +
	"\x11SpawnAgentRequest\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x01 \x01(\tR\tagentName\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\x12\x1b\n" +
	"\tparent_id\x18\x03 \x01(\tR\bparentId\"O\n" +
	"\x11StartAgentRequest\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x01 \x01(\tR\tagentName\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\tR\bparentId\"3\n" +
	"\x12StartAgentResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"f\n" +
	"\x12SendMessageRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1b\n" +
	"\tcaller_id\x18\x03 \x01(\tR\bcallerId\"J\n" +
	"\x10StopAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1b\n" +
	"\tcaller_id\x18\x02 \x01(\tR\bcallerId\"\x13\n" +
	"\x11StopAgentResponse\"0\n" +
	"\x11ListAgentsRequest\x12\x1b\n" +
	"\tparent_id\x18\x01 \x01(\tR\bparentId\"B\n" +
	"\x12ListAgentsResponse\x12,\n" +
	"\x06agents\x18\x01 \x03(\v2\x14.hive.AgentInfoProtoR\x06agents\"\x87\x01\n" +
	"\x0eAgentInfoProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\tR\x04mode\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\tparent_id\x18\x05 \x01(\tR\bparentId\"\x13\n" +
	"\x11GetSecretsRequest\"<\n" +
	"\x12GetSecretsResponse\x12\x14\n" +
	"\x05names\x18\x01 \x03(\tR\x05names\x12\x10\n" +
	"\x03env\x18\x02 \x03(\tR\x03env\"'\n" +
	"\vChatRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x11\n" +
	"\x0fShutdownRequest\"\x12\n" +
	"\x10ShutdownResponse2\x82\x03\n" +
	"\tAgentHost\x128\n" +
	"\n" +
	"SpawnAgent\x12\x17.hive.SpawnAgentRequest\x1a\x0f.hive.ChatEvent0\x01\x12?\n" +
	"\n" +
	"StartAgent\x12\x17.hive.StartAgentRequest\x1a\x18.hive.StartAgentResponse\x12:\n" +
	"\vSendMessage\x12\x18.hive.SendMessageRequest\x1a\x0f.hive.ChatEvent0\x01\x12<\n" +
	"\tStopAgent\x12\x16.hive.StopAgentRequest\x1a\x17.hive.StopAgentResponse\x12?\n" +
	"\n" +
	"ListAgents\x12\x17.hive.ListAgentsRequest\x1a\x18.hive.ListAgentsResponse\x12?\n" +
	"\n" +
	"GetSecrets\x12\x17.hive.GetSecretsRequest\x1a\x18.hive.GetSecretsResponse2v\n" +
	"\vAgentWorker\x12,\n" +
	"\x04Chat\x12\x11.hive.ChatRequest\x1a\x0f.hive.ChatEvent0\x01\x129\n" +
	"\bShutdown\x12\x15.hive.ShutdownRequest\x1a\x16.hive.ShutdownResponseB0Z.github.com/nchapman/hivebot/internal/ipc/protob\x06proto3"

var (
	file_internal_ipc_proto_hive_proto_rawDescOnce sync.Once
	file_internal_ipc_proto_hive_proto_rawDescData []byte
)

func file_internal_ipc_proto_hive_proto_rawDescGZIP() []byte {
	file_internal_ipc_proto_hive_proto_rawDescOnce.Do(func() {
		file_internal_ipc_proto_hive_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_ipc_proto_hive_proto_rawDesc), len(file_internal_ipc_proto_hive_proto_rawDesc)))
	})
	return file_internal_ipc_proto_hive_proto_rawDescData
}

var file_internal_ipc_proto_hive_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_internal_ipc_proto_hive_proto_goTypes = []any{
	(*ChatEvent)(nil),          // 0: hive.ChatEvent
	(*SpawnAgentRequest)(nil),  // 1: hive.SpawnAgentRequest
	(*StartAgentRequest)(nil),  // 2: hive.StartAgentRequest
	(*StartAgentResponse)(nil), // 3: hive.StartAgentResponse
	(*SendMessageRequest)(nil), // 4: hive.SendMessageRequest
	(*StopAgentRequest)(nil),   // 5: hive.StopAgentRequest
	(*StopAgentResponse)(nil),  // 6: hive.StopAgentResponse
	(*ListAgentsRequest)(nil),  // 7: hive.ListAgentsRequest
	(*ListAgentsResponse)(nil), // 8: hive.ListAgentsResponse
	(*AgentInfoProto)(nil),     // 9: hive.AgentInfoProto
	(*GetSecretsRequest)(nil),  // 10: hive.GetSecretsRequest
	(*GetSecretsResponse)(nil), // 11: hive.GetSecretsResponse
	(*ChatRequest)(nil),        // 12: hive.ChatRequest
	(*ShutdownRequest)(nil),    // 13: hive.ShutdownRequest
	(*ShutdownResponse)(nil),   // 14: hive.ShutdownResponse
}
var file_internal_ipc_proto_hive_proto_depIdxs = []int32{
	9,  // 0: hive.ListAgentsResponse.agents:type_name -> hive.AgentInfoProto
	1,  // 1: hive.AgentHost.SpawnAgent:input_type -> hive.SpawnAgentRequest
	2,  // 2: hive.AgentHost.StartAgent:input_type -> hive.StartAgentRequest
	4,  // 3: hive.AgentHost.SendMessage:input_type -> hive.SendMessageRequest
	5,  // 4: hive.AgentHost.StopAgent:input_type -> hive.StopAgentRequest
	7,  // 5: hive.AgentHost.ListAgents:input_type -> hive.ListAgentsRequest
	10, // 6: hive.AgentHost.GetSecrets:input_type -> hive.GetSecretsRequest
	12, // 7: hive.AgentWorker.Chat:input_type -> hive.ChatRequest
	13, // 8: hive.AgentWorker.Shutdown:input_type -> hive.ShutdownRequest
	0,  // 9: hive.AgentHost.SpawnAgent:output_type -> hive.ChatEvent
	3,  // 10: hive.AgentHost.StartAgent:output_type -> hive.StartAgentResponse
	0,  // 11: hive.AgentHost.SendMessage:output_type -> hive.ChatEvent
	6,  // 12: hive.AgentHost.StopAgent:output_type -> hive.StopAgentResponse
	8,  // 13: hive.AgentHost.ListAgents:output_type -> hive.ListAgentsResponse
	11, // 14: hive.AgentHost.GetSecrets:output_type -> hive.GetSecretsResponse
	0,  // 15: hive.AgentWorker.Chat:output_type -> hive.ChatEvent
	14, // 16: hive.AgentWorker.Shutdown:output_type -> hive.ShutdownResponse
	9,  // [9:17] is the sub-list for method output_type
	1,  // [1:9] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_internal_ipc_proto_hive_proto_init() }
func file_internal_ipc_proto_hive_proto_init() {
	if File_internal_ipc_proto_hive_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_ipc_proto_hive_proto_rawDesc), len(file_internal_ipc_proto_hive_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_internal_ipc_proto_hive_proto_goTypes,
		DependencyIndexes: file_internal_ipc_proto_hive_proto_depIdxs,
		MessageInfos:      file_internal_ipc_proto_hive_proto_msgTypes,
	}.Build()
	File_internal_ipc_proto_hive_proto = out.File
	file_internal_ipc_proto_hive_proto_goTypes = nil
	file_internal_ipc_proto_hive_proto_depIdxs = nil
}
