// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: internal/ipc/proto/hive.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentHost_SpawnAgent_FullMethodName  = "/hive.AgentHost/SpawnAgent"
	AgentHost_StartAgent_FullMethodName  = "/hive.AgentHost/StartAgent"
	AgentHost_SendMessage_FullMethodName = "/hive.AgentHost/SendMessage"
	AgentHost_StopAgent_FullMethodName   = "/hive.AgentHost/StopAgent"
	AgentHost_ListAgents_FullMethodName  = "/hive.AgentHost/ListAgents"
	AgentHost_GetSecrets_FullMethodName  = "/hive.AgentHost/GetSecrets"
)

// AgentHostClient is the client API for AgentHost service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentHost is served by the control plane. Agent processes call these RPCs
// to perform manager-level operations (spawning agents, sending messages, etc.).
type AgentHostClient interface {
	// SpawnAgent runs an ephemeral subagent to completion, streaming deltas.
	SpawnAgent(ctx context.Context, in *SpawnAgentRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatEvent], error)
	// StartAgent starts a persistent child agent.
	StartAgent(ctx context.Context, in *StartAgentRequest, opts ...grpc.CallOption) (*StartAgentResponse, error)
	// SendMessage sends a message to a running agent, streaming deltas.
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatEvent], error)
	// StopAgent stops an agent and its subtree.
	StopAgent(ctx context.Context, in *StopAgentRequest, opts ...grpc.CallOption) (*StopAgentResponse, error)
	// ListAgents returns the direct children of a parent agent.
	ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*ListAgentsResponse, error)
	// GetSecrets returns secret names and env vars for bash injection.
	GetSecrets(ctx context.Context, in *GetSecretsRequest, opts ...grpc.CallOption) (*GetSecretsResponse, error)
}

type agentHostClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentHostClient(cc grpc.ClientConnInterface) AgentHostClient {
	return &agentHostClient{cc}
}

func (c *agentHostClient) SpawnAgent(ctx context.Context, in *SpawnAgentRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentHost_ServiceDesc.Streams[0], AgentHost_SpawnAgent_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SpawnAgentRequest, ChatEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentHost_SpawnAgentClient = grpc.ServerStreamingClient[ChatEvent]

func (c *agentHostClient) StartAgent(ctx context.Context, in *StartAgentRequest, opts ...grpc.CallOption) (*StartAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartAgentResponse)
	err := c.cc.Invoke(ctx, AgentHost_StartAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentHostClient) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentHost_ServiceDesc.Streams[1], AgentHost_SendMessage_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SendMessageRequest, ChatEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentHost_SendMessageClient = grpc.ServerStreamingClient[ChatEvent]

func (c *agentHostClient) StopAgent(ctx context.Context, in *StopAgentRequest, opts ...grpc.CallOption) (*StopAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopAgentResponse)
	err := c.cc.Invoke(ctx, AgentHost_StopAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentHostClient) ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*ListAgentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAgentsResponse)
	err := c.cc.Invoke(ctx, AgentHost_ListAgents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentHostClient) GetSecrets(ctx context.Context, in *GetSecretsRequest, opts ...grpc.CallOption) (*GetSecretsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSecretsResponse)
	err := c.cc.Invoke(ctx, AgentHost_GetSecrets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentHostServer is the server API for AgentHost service.
// All implementations must embed UnimplementedAgentHostServer
// for forward compatibility.
//
// AgentHost is served by the control plane. Agent processes call these RPCs
// to perform manager-level operations (spawning agents, sending messages, etc.).
type AgentHostServer interface {
	// SpawnAgent runs an ephemeral subagent to completion, streaming deltas.
	SpawnAgent(*SpawnAgentRequest, grpc.ServerStreamingServer[ChatEvent]) error
	// StartAgent starts a persistent child agent.
	StartAgent(context.Context, *StartAgentRequest) (*StartAgentResponse, error)
	// SendMessage sends a message to a running agent, streaming deltas.
	SendMessage(*SendMessageRequest, grpc.ServerStreamingServer[ChatEvent]) error
	// StopAgent stops an agent and its subtree.
	StopAgent(context.Context, *StopAgentRequest) (*StopAgentResponse, error)
	// ListAgents returns the direct children of a parent agent.
	ListAgents(context.Context, *ListAgentsRequest) (*ListAgentsResponse, error)
	// GetSecrets returns secret names and env vars for bash injection.
	GetSecrets(context.Context, *GetSecretsRequest) (*GetSecretsResponse, error)
	mustEmbedUnimplementedAgentHostServer()
}

// UnimplementedAgentHostServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentHostServer struct{}

func (UnimplementedAgentHostServer) SpawnAgent(*SpawnAgentRequest, grpc.ServerStreamingServer[ChatEvent]) error {
	return status.Error(codes.Unimplemented, "method SpawnAgent not implemented")
}
func (UnimplementedAgentHostServer) StartAgent(context.Context, *StartAgentRequest) (*StartAgentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartAgent not implemented")
}
func (UnimplementedAgentHostServer) SendMessage(*SendMessageRequest, grpc.ServerStreamingServer[ChatEvent]) error {
	return status.Error(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedAgentHostServer) StopAgent(context.Context, *StopAgentRequest) (*StopAgentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopAgent not implemented")
}
func (UnimplementedAgentHostServer) ListAgents(context.Context, *ListAgentsRequest) (*ListAgentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAgents not implemented")
}
func (UnimplementedAgentHostServer) GetSecrets(context.Context, *GetSecretsRequest) (*GetSecretsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSecrets not implemented")
}
func (UnimplementedAgentHostServer) mustEmbedUnimplementedAgentHostServer() {}
func (UnimplementedAgentHostServer) testEmbeddedByValue()                   {}

// UnsafeAgentHostServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentHostServer will
// result in compilation errors.
type UnsafeAgentHostServer interface {
	mustEmbedUnimplementedAgentHostServer()
}

func RegisterAgentHostServer(s grpc.ServiceRegistrar, srv AgentHostServer) {
	// If the following call panics, it indicates UnimplementedAgentHostServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentHost_ServiceDesc, srv)
}

func _AgentHost_SpawnAgent_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SpawnAgentRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentHostServer).SpawnAgent(m, &grpc.GenericServerStream[SpawnAgentRequest, ChatEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentHost_SpawnAgentServer = grpc.ServerStreamingServer[ChatEvent]

func _AgentHost_StartAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentHostServer).StartAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentHost_StartAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentHostServer).StartAgent(ctx, req.(*StartAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentHost_SendMessage_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SendMessageRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentHostServer).SendMessage(m, &grpc.GenericServerStream[SendMessageRequest, ChatEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentHost_SendMessageServer = grpc.ServerStreamingServer[ChatEvent]

func _AgentHost_StopAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentHostServer).StopAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentHost_StopAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentHostServer).StopAgent(ctx, req.(*StopAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentHost_ListAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAgentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentHostServer).ListAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentHost_ListAgents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentHostServer).ListAgents(ctx, req.(*ListAgentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentHost_GetSecrets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSecretsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentHostServer).GetSecrets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentHost_GetSecrets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentHostServer).GetSecrets(ctx, req.(*GetSecretsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentHost_ServiceDesc is the grpc.ServiceDesc for AgentHost service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentHost_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hive.AgentHost",
	HandlerType: (*AgentHostServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartAgent",
			Handler:    _AgentHost_StartAgent_Handler,
		},
		{
			MethodName: "StopAgent",
			Handler:    _AgentHost_StopAgent_Handler,
		},
		{
			MethodName: "ListAgents",
			Handler:    _AgentHost_ListAgents_Handler,
		},
		{
			MethodName: "GetSecrets",
			Handler:    _AgentHost_GetSecrets_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SpawnAgent",
			Handler:       _AgentHost_SpawnAgent_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SendMessage",
			Handler:       _AgentHost_SendMessage_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/ipc/proto/hive.proto",
}

const (
	AgentWorker_Chat_FullMethodName     = "/hive.AgentWorker/Chat"
	AgentWorker_Shutdown_FullMethodName = "/hive.AgentWorker/Shutdown"
)

// AgentWorkerClient is the client API for AgentWorker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentWorker is served by each agent process. The control plane calls these
// RPCs to send messages and manage the agent's lifecycle.
type AgentWorkerClient interface {
	// Chat sends a message and streams back deltas and the final response.
	Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatEvent], error)
	// Shutdown gracefully stops the agent worker process.
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error)
}

type agentWorkerClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentWorkerClient(cc grpc.ClientConnInterface) AgentWorkerClient {
	return &agentWorkerClient{cc}
}

func (c *agentWorkerClient) Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentWorker_ServiceDesc.Streams[0], AgentWorker_Chat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatRequest, ChatEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentWorker_ChatClient = grpc.ServerStreamingClient[ChatEvent]

func (c *agentWorkerClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShutdownResponse)
	err := c.cc.Invoke(ctx, AgentWorker_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentWorkerServer is the server API for AgentWorker service.
// All implementations must embed UnimplementedAgentWorkerServer
// for forward compatibility.
//
// AgentWorker is served by each agent process. The control plane calls these
// RPCs to send messages and manage the agent's lifecycle.
type AgentWorkerServer interface {
	// Chat sends a message and streams back deltas and the final response.
	Chat(*ChatRequest, grpc.ServerStreamingServer[ChatEvent]) error
	// Shutdown gracefully stops the agent worker process.
	Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error)
	mustEmbedUnimplementedAgentWorkerServer()
}

// UnimplementedAgentWorkerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentWorkerServer struct{}

func (UnimplementedAgentWorkerServer) Chat(*ChatRequest, grpc.ServerStreamingServer[ChatEvent]) error {
	return status.Error(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedAgentWorkerServer) Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedAgentWorkerServer) mustEmbedUnimplementedAgentWorkerServer() {}
func (UnimplementedAgentWorkerServer) testEmbeddedByValue()                     {}

// UnsafeAgentWorkerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentWorkerServer will
// result in compilation errors.
type UnsafeAgentWorkerServer interface {
	mustEmbedUnimplementedAgentWorkerServer()
}

func RegisterAgentWorkerServer(s grpc.ServiceRegistrar, srv AgentWorkerServer) {
	// If the following call panics, it indicates UnimplementedAgentWorkerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentWorker_ServiceDesc, srv)
}

func _AgentWorker_Chat_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentWorkerServer).Chat(m, &grpc.GenericServerStream[ChatRequest, ChatEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentWorker_ChatServer = grpc.ServerStreamingServer[ChatEvent]

func _AgentWorker_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentWorkerServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentWorker_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentWorkerServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentWorker_ServiceDesc is the grpc.ServiceDesc for AgentWorker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentWorker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hive.AgentWorker",
	HandlerType: (*AgentWorkerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Shutdown",
			Handler:    _AgentWorker_Shutdown_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Chat",
			Handler:       _AgentWorker_Chat_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/ipc/proto/hive.proto",
}
