services:
  hiro:
    image: ghcr.io/nchapman/hiro:latest
    restart: unless-stopped
    init: true
    ports:
      - "8120:8120"
    volumes:
      - hiro:/hiro
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --label-enable --cleanup

volumes:
  hiro:
