#!/bin/sh
#
# Downloads Docker's default seccomp profile and applies Hiro's modifications.
# The result is a flat allowlist — capability-gated and arg-filtered entries
# from the upstream profile are either promoted to unconditional or dropped.
#
# Usage:
#   ./dev/update-seccomp.sh            # writes seccomp.json
#   make update-seccomp                # same, via make
#
# Source: https://github.com/moby/profiles/blob/main/seccomp/default.json
#
# Changes from Docker default:
#
# ADDED (more permissive — needed for per-agent namespace isolation):
#   clone    — removed CLONE_NEWUSER flag restriction (user namespace creation)
#   clone3   — allowed (Docker returns ENOSYS without CAP_SYS_ADMIN)
#   unshare  — allowed (Docker requires CAP_SYS_ADMIN)
#   setns    — allowed (Docker requires CAP_SYS_ADMIN)
#   mount    — allowed for control plane bind mounts (Docker requires CAP_SYS_ADMIN)
#   umount, umount2 — allowed for control plane cleanup
#   socket   — removed AF_VSOCK filter; AF_VSOCK requires a hypervisor
#              (not present in standard Docker)
#
# REMOVED (more restrictive — not needed, reduces attack surface):
#   chroot       — not needed
#   pivot_root   — not needed
#   personality  — not needed
#   fanotify_mark — unusable without fanotify_init (which is capability-gated)
#
# Per-worker seccomp-BPF (applied at the process level by the control plane)
# further restricts agent processes by blocking clone(CLONE_NEWUSER), clone3,
# unshare, setns, mount, umount2, ptrace, chroot, pivot_root, and kexec_load.
# So these syscalls are only available to the control plane, not to agents.
# Note: umount (legacy, distinct from umount2) has no syscall number on
# amd64/arm64 and the BPF architecture check kills 32-bit compat calls.
#
set -e

UPSTREAM_URL="https://raw.githubusercontent.com/moby/profiles/main/seccomp/default.json"

if ! command -v jq >/dev/null 2>&1; then
  echo "Error: jq is required. Install it with: brew install jq (macOS) or apt install jq (Linux)"
  exit 1
fi

# Download upstream profile.
echo "Downloading Docker default seccomp profile..."
UPSTREAM=$(curl -fsSL "$UPSTREAM_URL")

# Extract the main allowlist (first entry: action=ALLOW, no caps/args/includes).
# Then add syscalls we promote from capability-gated to unconditional.
ADD='["clone", "clone3", "unshare", "setns", "mount", "umount", "umount2", "socket"]'

# Syscalls to remove.
REMOVE='["chroot", "pivot_root", "personality", "fanotify_mark"]'

# Build sorted syscall list: upstream main allowlist + additions - removals.
# clone/clone3/unshare/setns/mount/umount/umount2 — promoted from capability-gated.
# socket — upstream blocks AF_VSOCK; harmless without a hypervisor (standard Docker).
SYSCALLS=$(echo "$UPSTREAM" | jq --argjson add "$ADD" --argjson remove "$REMOVE" '
  # Main allowlist: first syscalls entry with no includes, excludes, or args.
  [.syscalls[0].names[]] +

  # Arch-specific unconditional allows for our target architectures.
  [.syscalls[] |
    select(.action == "SCMP_ACT_ALLOW" and .includes.arches != null and
           (.includes.caps == null) and (.args == null) and
           (.includes.arches | any(. == "amd64" or . == "arm64" or . == "x86" or . == "x32"))) |
    .names[]] +

  # Our additions.
  $add |

  # Remove duplicates, then remove exclusions.
  unique |
  map(select(. as $s | $remove | index($s) | not))
')

# Generate the output profile.
jq -n --argjson syscalls "$SYSCALLS" '{
  defaultAction: "SCMP_ACT_ERRNO",
  defaultErrnoRet: 1,
  comment: "Docker default seccomp profile with Hiro modifications. Generated by dev/update-seccomp.sh — do not edit manually. See that script for the full list of changes from upstream.",
  archMap: [
    { architecture: "SCMP_ARCH_X86_64", subArchitectures: ["SCMP_ARCH_X86", "SCMP_ARCH_X32"] },
    { architecture: "SCMP_ARCH_AARCH64", subArchitectures: ["SCMP_ARCH_ARM"] }
  ],
  syscalls: [
    {
      names: $syscalls,
      action: "SCMP_ACT_ALLOW"
    }
  ]
}' > seccomp.json

echo "Written seccomp.json ($(echo "$SYSCALLS" | jq length) syscalls)"

# Build the full set of syscalls Docker would allow for our architectures
# (main allowlist + arch-specific + capability-gated).
ALL_UPSTREAM=$(echo "$UPSTREAM" | jq '[.syscalls[] | select(.action == "SCMP_ACT_ALLOW") | .names[]] | unique')

# Show meaningful diff: what we allow that Docker wouldn't (without caps),
# and what Docker allows that we don't.
echo ""
echo "Promoted from capability-gated to unconditional:"
echo "$SYSCALLS" | jq -r --argjson upstream "$(echo "$UPSTREAM" | jq '[.syscalls[0].names[]]')" \
  '[.[] | select(. as $s | $upstream | index($s) | not)] | "  " + join(", ")'

echo ""
echo "Removed from Docker default:"
echo "$ALL_UPSTREAM" | jq -r --argjson ours "$SYSCALLS" --argjson add "$ADD" \
  '[.[] | select(. as $s | ($ours | index($s) | not) and ($add | index($s) | not))] | "  " + join(", ")'
